# Generated by Django 5.2.14 on 2026-09-23 02:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0191_collaboration_teams_and_notices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_key', models.UUIDField()),
                ('original_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('mime', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('text', models.TextField(blank=True)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('retry_key', models.UUIDField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'deleted_at'], name='work_material_owner'), models.Index(fields=['status', 'lease_until'], name='work_material_pending')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'upload_key'), name='work_upload_once')],
            },
        ),
    ]
