# Generated by Django 5.2.14 on 2026-09-23 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_collaboration_teams_and_notices'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workmaterial',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('recipient', models.CharField(max_length=200)),
                ('goal', models.TextField()),
                ('background', models.TextField(blank=True)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_key', models.UUIDField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(max_length=200)),
                ('base_url', models.URLField(max_length=500)),
                ('executor_version', models.CharField(default='communication-v1', max_length=40)),
                ('reserved_tokens', models.PositiveIntegerField()),
                ('max_output_tokens', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('call_started_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('usage_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.aiusagerecord')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='work.worktask')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('citations', models.JSONField(default=list)),
                ('origin', models.CharField(default='generated', max_length=16)),
                ('adopted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='work.workrun')),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('run', 'version'), name='work_artifact_version')],
            },
        ),
        migrations.CreateModel(
            name='WorkRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='work.workrun')),
            ],
            options={
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='work_event_seq')],
            },
        ),
        migrations.AddConstraint(
            model_name='worktask',
            constraint=models.UniqueConstraint(fields=('owner', 'request_key'), name='work_task_once'),
        ),
        migrations.AddIndex(
            model_name='workrun',
            index=models.Index(fields=['status', 'lease_until'], name='work_run_pending'),
        ),
        migrations.AddConstraint(
            model_name='workrun',
            constraint=models.UniqueConstraint(fields=('task', 'request_key'), name='work_run_once'),
        ),
    ]
