# Generated by Django 5.2.14 on 2026-10-06 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_workmaterial_locations_worktask_workrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrun',
            name='agent_deployment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workrun',
            name='agent_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workrun',
            name='agent_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workrun',
            name='agent_metering',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workrun',
            name='agent_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worktask',
            name='kind',
            field=models.CharField(default='communication', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkArtifactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='work.workrun')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('run', 'name'), name='work_run_file')],
            },
        ),
    ]
