# Generated by Django 5.2.14 on 2026-10-07 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_legacy_summary_run'),
        ('work', '0003_workrun_agent_deployment_workrun_agent_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workrun',
            name='artifact_manifest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workrun',
            name='execution_target',
            field=models.CharField(default='cloud', max_length=16),
        ),
        migrations.AddField(
            model_name='workrun',
            name='local_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workrun',
            name='local_report_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workrun',
            name='local_report_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workrun',
            name='usage_origin',
            field=models.CharField(default='provider', max_length=24),
        ),
        migrations.AddField(
            model_name='workrun',
            name='workspace_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='WorkDevice',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workrun',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='work.workdevice'),
        ),
    ]
