# Generated by Django 5.2.14 on 2026-10-07 02:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0004_workrun_artifact_manifest_workrun_execution_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrun",
            name="remote_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="WorkWorkspace",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=120)),
                ("model", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="work.workdevice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workrun",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="work.workworkspace",
            ),
        ),
    ]
