# Generated by Django 5.2.14 on 2026-10-07 04:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0196_legacy_summary_run"),
        ("work", "0005_workrun_remote_requested_workworkspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("selection", models.JSONField()),
                ("status", models.CharField(default="queued", max_length=16)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(max_length=200)),
                ("base_url", models.URLField(max_length=500)),
                (
                    "executor_version",
                    models.CharField(default="pi-review-v1", max_length=40),
                ),
                ("reserved_tokens", models.PositiveIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("input_tokens", models.PositiveIntegerField(null=True)),
                ("output_tokens", models.PositiveIntegerField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("call_started_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("agent_payload", models.JSONField(default=dict)),
                ("agent_deployment", models.JSONField(default=dict)),
                ("agent_metering", models.JSONField(default=dict)),
                ("agent_done", models.BooleanField(default=False)),
                ("agent_generation", models.PositiveIntegerField(default=0)),
                ("report", models.JSONField(default=dict)),
                (
                    "source_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="work.workrun",
                    ),
                ),
                (
                    "usage_record",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.aiusagerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["agent_done", "lease_until"], name="work_review_pending"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_run", "request_key"), name="work_review_once"
                    )
                ],
            },
        ),
    ]
