# Generated by Django 5.2.14 on 2026-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_pi_readonly_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrun',
            name='agent_deployment',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='agent_done',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='agent_generation',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='agent_metering',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='agent_payload',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='artifact_manifest',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='execution_target',
            field=models.CharField(db_default='cloud', default='cloud', max_length=16),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='local_claimed',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='local_report_hash',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='local_report_seq',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='remote_requested',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='usage_origin',
            field=models.CharField(db_default='provider', default='provider', max_length=24),
        ),
        migrations.AlterField(
            model_name='workrun',
            name='workspace_label',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='kind',
            field=models.CharField(db_default='communication', default='communication', max_length=20),
        ),
    ]
