// Web-generated slug: 10 lowercase letters grouped 3-4-3 ("abc-defg-hij").
export const roomIdPattern = '[a-z]{3}-[a-z]{4}-[a-z]{3}'

// 8-digit numeric meeting code generated by the backend for App-created rooms
// (see Room.generate_unique_slug on the backend). Both formats live in the
// room.slug column on the server side, so either is a valid path segment.
export const numericRoomIdPattern = '[0-9]{8}'

// Case-insensitive and with optional hyphens.  Accepts the legacy 10-char
// segmented slug AND the 8-digit numeric meeting code so that both formats
// resolve to the room route.
export const flexibleRoomIdPattern =
  '(?:[a-zA-Z0-9]{3}-?[a-zA-Z0-9]{4}-?[a-zA-Z0-9]{3}|[0-9]{8})'

const roomRegex = new RegExp(`^${roomIdPattern}$`)
const numericRoomRegex = new RegExp(`^${numericRoomIdPattern}$`)
const combinedPathPattern = `(?:${roomIdPattern}|${numericRoomIdPattern})`

export const isRoomValid = (roomIdOrUrl: string) =>
  roomRegex.test(roomIdOrUrl) ||
  numericRoomRegex.test(roomIdOrUrl) ||
  new RegExp(`^${window.location.origin}/${combinedPathPattern}$`).test(
    roomIdOrUrl
  )

export const normalizeRoomId = (roomId: string) => {
  // 8-digit numeric meeting codes are often displayed with a space ("1234 5678"
  // — see the Android history detail screen) or with a hyphen. Strip both and
  // we're back to a valid slug.
  const digitsOnly = roomId.replace(/[\s-]/g, '')
  if (numericRoomRegex.test(digitsOnly)) {
    return digitsOnly
  }
  const cleanId = roomId.toLowerCase().replace(/-/g, '')
  if (cleanId.length === 10) {
    return `${cleanId.slice(0, 3)}-${cleanId.slice(3, 7)}-${cleanId.slice(7, 10)}`
  }
  return roomId
}
