import type { ClientRequest, ClientRequestConstructorOptions } from "electron";
import { Readable, Writable } from "node:stream";
import { pipeline } from "node:stream/promises";

function responseHeaders(raw: Record<string, string | string[]>) {
  const headers = new Headers();
  for (const [name, values] of Object.entries(raw))
    for (const value of Array.isArray(values) ? values : [values]) headers.append(name, value);
  // Chromium has decoded the response body before it reaches IncomingMessage.
  headers.delete("content-encoding");
  headers.delete("content-length");
  return headers;
}

/** Return redirects to Chromium instead of hiding the final navigation URL.
 * Keep this session's cookie handling; never attach the native Meet bearer.
 */
export function forwardRequest(
  request: Request,
  createRequest: (options: ClientRequestConstructorOptions) => ClientRequest,
): Promise<Response> {
  return new Promise((resolve, reject) => {
    const origin = request.headers.get("origin") || undefined;
    const outgoing = createRequest({
      url: request.url, method: request.method, origin,
      credentials: request.credentials === "same-origin" && !origin ? "include" : request.credentials,
      redirect: "manual", bypassCustomProtocolHandlers: true,
      referrerPolicy: request.referrerPolicy, cache: request.cache,
    });
    // Browser-provided transport headers are regenerated by Chromium.
    const managed = new Set(["content-length", "host", "trailer", "te", "upgrade", "cookie2", "keep-alive", "transfer-encoding", "connection"]);
    for (const [name, value] of request.headers)
      if (!managed.has(name.toLowerCase())) outgoing.setHeader(name, value);
    let settled = false;
    const fail = (error: Error) => { if (!settled) { settled = true; reject(error); } };
    outgoing.on("error", fail);
    const abort = () => { fail(new Error("Request aborted")); outgoing.abort(); };
    request.signal.addEventListener("abort", abort, { once: true });
    outgoing.once("close", () => request.signal.removeEventListener("abort", abort));
    outgoing.on("redirect", (status, _method, url, rawHeaders) => {
      const headers = responseHeaders(rawHeaders);
      headers.set("location", url);
      settled = true;
      resolve(new Response(null, { status, headers }));
      // Do not follow. Its cancellation error is consumed by the listener above.
    });
    outgoing.on("response", incoming => {
      const body = request.method === "HEAD" || [204, 205, 304].includes(incoming.statusCode)
        ? null : Readable.toWeb(incoming as unknown as Readable) as ReadableStream<Uint8Array>;
      settled = true;
      resolve(new Response(body, { status: incoming.statusCode, headers: responseHeaders(incoming.headers) }));
    });
    if (request.signal.aborted) { abort(); return; }
    if (request.body) {
      outgoing.chunkedEncoding = true;
      void pipeline(Readable.fromWeb(request.body as import("node:stream/web").ReadableStream), outgoing as unknown as Writable).catch(fail);
    } else outgoing.end();
  });
}
