# Generated by Django 5.2.14 on 2026-06-22 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_transcriptchunk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('primary_domain', models.CharField(blank=True, default='', help_text="Primary email domain (e.g. 'example.com'). Used to auto-place invited members whose email matches.", max_length=255, verbose_name='primary email domain')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='settings')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'meet_organization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=1024, verbose_name='path')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='depth')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('team_key', models.CharField(editable=False, max_length=100, unique=True, verbose_name='team key')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('head', models.ForeignKey(blank=True, help_text='Department head — the default approver for org workflows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'meet_department',
                'ordering': ('path', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('is_primary', models.BooleanField(default=False, help_text="The user's primary department within the organization.", verbose_name='primary')),
                ('org_role', models.CharField(choices=[('member', 'Member'), ('dept_admin', 'Department administrator'), ('administrator', 'Organization administrator'), ('owner', 'Organization owner')], default='member', max_length=20)),
                ('employee_no', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended'), ('left', 'Left')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, help_text='Null means an organization-level membership (no department).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'meet_membership',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'department'), name='membership_unique_user_department', violation_error_message='This user already belongs to this department.'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'organization'), name='membership_one_primary_per_user_org', violation_error_message='A user can have only one primary department per organization.')],
            },
        ),
    ]
