# Generated by Django 5.2.14 on 2026-06-22 13:22
#
# Data migration — P1-b: bootstrap a single default Organization and give every
# existing user a primary, organization-level Membership. This is what makes
# User.get_teams() (wired in P1-c) return real department keys for the existing
# user base; org-level members simply have no department yet and get one via the
# admin console / directory later.
#
# Idempotent: re-running creates nothing it already created. Reversible: the
# reverse removes the bootstrapped organization (cascading its memberships).

from django.conf import settings
from django.db import migrations
from django.utils import timezone

# Overridable via settings without editing this migration; sensible defaults so
# a fresh deploy needs no extra configuration.
DEFAULT_ORG_SLUG = getattr(settings, "ORGANIZATION_BOOTSTRAP_SLUG", "default")
DEFAULT_ORG_NAME = getattr(
    settings, "ORGANIZATION_BOOTSTRAP_NAME", "Default Organization"
)


def bootstrap_default_organization(apps, schema_editor):
    """Create the default org and a primary membership for each existing user."""
    Organization = apps.get_model("core", "Organization")
    User = apps.get_model("core", "User")
    Membership = apps.get_model("core", "Membership")

    org, _created = Organization.objects.get_or_create(
        slug=DEFAULT_ORG_SLUG, defaults={"name": DEFAULT_ORG_NAME}
    )

    already = set(
        Membership.objects.filter(organization=org).values_list("user_id", flat=True)
    )
    now = timezone.now()
    to_create = [
        Membership(
            organization=org,
            user=user,
            department=None,  # organization-level until placed in a department
            is_primary=True,
            org_role="administrator" if user.is_staff else "member",
            status="active",
            joined_at=user.created_at or now,
        )
        for user in User.objects.exclude(id__in=already).iterator()
    ]
    Membership.objects.bulk_create(to_create, batch_size=500)


def remove_default_organization(apps, schema_editor):
    """Reverse: drop the bootstrapped organization (memberships cascade)."""
    Organization = apps.get_model("core", "Organization")
    Organization.objects.filter(slug=DEFAULT_ORG_SLUG).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_organization_department_membership"),
    ]

    operations = [
        migrations.RunPython(
            bootstrap_default_organization,
            reverse_code=remove_default_organization,
        ),
    ]
