# Generated by Django 5.2.14 on 2026-07-04 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed')], max_length=40),
        ),
        migrations.CreateModel(
            name='OrgInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('org_role', models.CharField(choices=[('member', 'Member'), ('dept_admin', 'Department administrator'), ('administrator', 'Organization administrator'), ('owner', 'Organization owner')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department the invitee lands in (null = organization-level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='core.department')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
            options={
                'verbose_name': 'Organization invitation',
                'verbose_name_plural': 'Organization invitations',
                'db_table': 'meet_org_invitation',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='one_pending_invite_per_email_org', violation_error_message='A pending invitation already exists for this email.')],
            },
        ),
    ]
