# Generated by Django 5.2.14 on 2026-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_devicepushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Mobile number, authoritative copy in Keycloak (phoneNumber attribute); synced here on each login by the OIDC backend. Empty for accounts without a phone (email/device users). Same-org visible, masked by default — full number only via the reveal endpoint (P3).', max_length=32, verbose_name='phone'),
        ),
    ]
