# Generated by Django 5.2.14 on 2026-07-18 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_summary_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInvitee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('source', models.CharField(choices=[('group', 'group'), ('manual', 'manual')], default='manual', max_length=16)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='core.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room invitee',
                'verbose_name_plural': 'Room invitees',
                'db_table': 'meet_room_invitee',
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='one_invite_per_room_user')],
            },
        ),
    ]
