# Generated by Django 5.2.14 on 2026-07-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_roominvitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='source_conversation_id',
            field=models.CharField(blank=True, default='', help_text='IM conversation this event was created from; change cards are pushed back to it (best-effort).', max_length=64, verbose_name='source conversation id'),
        ),
    ]
