# Generated by Django 5.2.14 on 2026-07-25 08:49

import core.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_btree_gist_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoomFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('code', models.CharField(blank=True, default='', help_text='Stable key the clients map to an icon (tv, projector, ...).', max_length=32, verbose_name='code')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_facilities', to='core.organization')),
            ],
            options={
                'verbose_name': 'Meeting room facility',
                'verbose_name_plural': 'Meeting room facilities',
                'db_table': 'meet_meeting_room_facility',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('path', models.CharField(blank=True, db_index=True, default='', max_length=1024, verbose_name='path')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='depth')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', help_text='Empty inherits from the nearest ancestor that sets one.', null=True, use_pytz=False, verbose_name='timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_nodes', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.meetingroomnode')),
            ],
            options={
                'verbose_name': 'Meeting room node',
                'verbose_name_plural': 'Meeting room nodes',
                'db_table': 'meet_meeting_room_node',
                'ordering': ('path', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='code')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 means unspecified.', verbose_name='capacity')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='disabled reason')),
                ('booking_scope', models.CharField(choices=[('org', 'Whole organization'), ('departments', 'Selected departments')], default='org', max_length=20)),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires approval')),
                ('max_booking_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('advance_booking_days', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('approval_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_rooms', to='core.approvaltemplate')),
                ('bookable_departments', models.ManyToManyField(blank=True, db_table='meet_meeting_room_department', related_name='bookable_meeting_rooms', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='core.organization')),
                ('facilities', models.ManyToManyField(blank=True, db_table='meet_meeting_room_facility_link', related_name='rooms', to='core.meetingroomfacility')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.meetingroomnode')),
            ],
            options={
                'verbose_name': 'Meeting room',
                'verbose_name_plural': 'Meeting rooms',
                'db_table': 'meet_meeting_room',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('start_at', models.DateTimeField(verbose_name='start at')),
                ('end_at', models.DateTimeField(verbose_name='end at')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending approval'), ('conflict', 'Conflicted'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('source', models.CharField(choices=[('event', 'Calendar event'), ('manual', 'Manual'), ('maintenance', 'Maintenance')], default='event', max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='Label for manual / maintenance holds; event holds read the event.', max_length=255, verbose_name='title')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approval_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_room_bookings', to='core.approvalinstance')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_room_bookings', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Null for a manual / maintenance hold (M2).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to='core.calendarevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_bookings', to='core.organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.meetingroom')),
            ],
            options={
                'verbose_name': 'Meeting room booking',
                'verbose_name_plural': 'Meeting room bookings',
                'db_table': 'meet_meeting_room_booking',
                'ordering': ('start_at',),
                'indexes': [models.Index(fields=['room', 'start_at'], name='mrbooking_room_start_idx'), models.Index(fields=['organization', 'start_at'], name='mrbooking_org_start_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='mrbooking_end_after_start', violation_error_message='End must be after start.'), models.UniqueConstraint(condition=models.Q(('event__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('event', 'room'), name='mrbooking_uniq_event_room'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), expressions=[('room', '='), (core.models.TsTzRange('start_at', 'end_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='mrbooking_no_overlap', violation_error_message='This meeting room is already booked for that time.')],
            },
        ),
        migrations.AddConstraint(
            model_name='meetingroomfacility',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='mrfacility_uniq_org_name', violation_error_message='A facility with this name already exists.'),
        ),
        migrations.AddIndex(
            model_name='meetingroomnode',
            index=models.Index(fields=['organization', 'path'], name='mrnode_org_path_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingroom',
            index=models.Index(fields=['organization', 'is_active'], name='mroom_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingroom',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('code', ''), _negated=True)), fields=('organization', 'code'), name='mroom_uniq_org_code', violation_error_message='A room with this code already exists.'),
        ),
    ]
