# Generated by Django 5.2.14 on 2026-08-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_contact_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingaccess',
            name='team',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
