# Generated by Django 5.2.14 on 2026-08-01 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_baseaccess_team_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDictItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('scope', models.CharField(choices=[('employee_type', 'Employee type'), ('job_level', 'Job level'), ('job_sequence', 'Job sequence'), ('onboard_type', 'Onboarding type'), ('probation_status', 'Probation status'), ('leave_reason', 'Leave reason')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False, help_text='Seeded option: the label may be renamed but it cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization dictionary item',
                'verbose_name_plural': 'Organization dictionary items',
                'db_table': 'meet_org_dict_item',
                'ordering': ('scope', 'sort_order', 'code'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='department code'),
        ),
        migrations.AddField(
            model_name='department',
            name='source',
            field=models.CharField(choices=[('manual', 'Created manually'), ('import', 'Bulk import'), ('api', 'Open API'), ('sync', 'External sync'), ('invite', 'Created by invitation')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='membership',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='dotted_manager',
            field=models.ForeignKey(blank=True, help_text='Dotted-line manager. Never used for automatic approval routing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotted_reports', to='core.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='membership',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='left_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='left_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='left_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='membership',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='core.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='source',
            field=models.CharField(choices=[('manual', 'Created manually'), ('import', 'Bulk import'), ('api', 'Open API'), ('sync', 'External sync'), ('invite', 'Created by invitation')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_city',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_station',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), ('deleted_at__isnull', True)), fields=('organization', 'code'), name='department_unique_org_code', violation_error_message='This organization already has a department with this code.'),
        ),
        migrations.AddField(
            model_name='orgdictitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dict_items', to='core.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='employee_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'scope': 'employee_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgdictitem'),
        ),
        migrations.AddField(
            model_name='membership',
            name='job_level',
            field=models.ForeignKey(blank=True, limit_choices_to={'scope': 'job_level'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgdictitem'),
        ),
        migrations.AddField(
            model_name='membership',
            name='job_sequence',
            field=models.ForeignKey(blank=True, limit_choices_to={'scope': 'job_sequence'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.orgdictitem'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'status', 'employee_type'], name='meet_member_organiz_b83b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'status', 'left_at'], name='meet_member_organiz_e9d769_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['manager'], name='meet_member_manager_c14c41_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_no', ''), _negated=True), fields=('organization', 'employee_no'), name='membership_unique_employee_no', violation_error_message='This employee number is already used in this organization.'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('manager', models.F('id')), _negated=True), name='membership_manager_not_self', violation_error_message='A member cannot be their own manager.'),
        ),
        migrations.AddConstraint(
            model_name='orgdictitem',
            constraint=models.UniqueConstraint(fields=('organization', 'scope', 'code'), name='dict_item_unique_org_scope_code', violation_error_message='This organization already has an option with this code.'),
        ),
    ]
