# Generated by Django 5.2.14 on 2026-08-01 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_seed_employee_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('group_key', models.CharField(editable=False, max_length=100, unique=True, verbose_name='group key')),
                ('source', models.CharField(choices=[('manual', 'Created manually'), ('import', 'Bulk import'), ('api', 'Open API'), ('sync', 'External sync'), ('invite', 'Created by invitation')], default='manual', max_length=16)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='core.organization')),
            ],
            options={
                'verbose_name': 'User group',
                'verbose_name_plural': 'User groups',
                'db_table': 'meet_user_group',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User group member',
                'verbose_name_plural': 'User group members',
                'db_table': 'meet_user_group_member',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='user_group_unique_org_name', violation_error_message='This organization already has a group with this name.'),
        ),
        migrations.AddIndex(
            model_name='usergroupmember',
            index=models.Index(fields=['user'], name='ugm_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='usergroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='user_group_member_unique', violation_error_message='This person is already in the group.'),
        ),
    ]
