# Generated by Django 5.2.14 on 2026-08-01 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('role.create', 'Admin role created'), ('role.update', 'Admin role updated'), ('role.delete', 'Admin role deleted'), ('role.assign', 'Admin role assigned'), ('role.unassign', 'Admin role revoked'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('code', models.SlugField(max_length=40, verbose_name='code')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='permissions')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='built-in')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to='core.organization')),
            ],
            options={
                'verbose_name': 'Admin role',
                'verbose_name_plural': 'Admin roles',
                'db_table': 'meet_admin_role',
                'ordering': ('-is_builtin', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AdminRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('scope_type', models.CharField(choices=[('all', 'Whole organization'), ('departments', 'Selected departments')], default='all', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_role_assignments', to='core.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.adminrole')),
            ],
            options={
                'verbose_name': 'Admin role assignment',
                'verbose_name_plural': 'Admin role assignments',
                'db_table': 'meet_admin_role_assignment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AdminRoleScopeDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_departments', to='core.adminroleassignment')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.department')),
            ],
            options={
                'verbose_name': 'Admin role scope department',
                'verbose_name_plural': 'Admin role scope departments',
                'db_table': 'meet_admin_role_scope_department',
            },
        ),
        migrations.AddConstraint(
            model_name='adminrole',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='admin_role_unique_org_code', violation_error_message='This organization already has a role with this code.'),
        ),
        migrations.AddIndex(
            model_name='adminroleassignment',
            index=models.Index(fields=['membership'], name='admin_role_asg_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='adminroleassignment',
            constraint=models.UniqueConstraint(fields=('role', 'membership'), name='admin_role_assignment_unique', violation_error_message='This person already holds this role.'),
        ),
        migrations.AddConstraint(
            model_name='adminrolescopedepartment',
            constraint=models.UniqueConstraint(fields=('assignment', 'department'), name='admin_role_scope_unique'),
        ),
    ]
