# Generated by Django 5.2.14 on 2026-08-01 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_seed_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('role.create', 'Admin role created'), ('role.update', 'Admin role updated'), ('role.delete', 'Admin role deleted'), ('role.assign', 'Admin role assigned'), ('role.unassign', 'Admin role revoked'), ('member.import', 'Members imported'), ('member.export', 'Members exported'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('filename', models.CharField(blank=True, default='', max_length=255, verbose_name='file name')),
                ('status', models.CharField(choices=[('pending', 'Queued for preflight'), ('previewing', 'Checking the file'), ('previewed', 'Checked — awaiting confirmation'), ('applying', 'Applying'), ('done', 'Applied'), ('partial', 'Applied with errors'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('source', models.TextField(blank=True, default='')),
                ('create_missing_departments', models.BooleanField(default=False)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.organization')),
            ],
            options={
                'verbose_name': 'Import job',
                'verbose_name_plural': 'Import jobs',
                'db_table': 'meet_import_job',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='import_job_org_idx')],
            },
        ),
    ]
