# Generated by Django 5.2.14 on 2026-08-02 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='price_input_per_mtok',
            field=models.PositiveIntegerField(default=0, verbose_name='input price per million tokens (micro-CNY)'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='price_output_per_mtok',
            field=models.PositiveIntegerField(default=0, verbose_name='output price per million tokens (micro-CNY)'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='price_per_minute',
            field=models.PositiveIntegerField(default=0, help_text='Used by STT / TTS models, which are billed by duration.', verbose_name='audio price per minute (micro-CNY)'),
        ),
        migrations.AddField(
            model_name='room',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.organization'),
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('kind', models.CharField(choices=[('summary', 'Meeting summary'), ('global_ask', 'Ask across content'), ('personal_ai', 'Personal assistant'), ('room_ai', 'In-meeting assistant'), ('other', 'Other')], default='other', max_length=16)),
                ('model_code', models.CharField(blank=True, default='', max_length=128)),
                ('ref_type', models.CharField(blank=True, default='', max_length=32)),
                ('ref_id', models.CharField(blank=True, default='', max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('audio_seconds', models.PositiveIntegerField(default=0)),
                ('cost_micros', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI usage record',
                'verbose_name_plural': 'AI usage records',
                'db_table': 'meet_ai_usage_record',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='ai_usage_org_time_idx'), models.Index(fields=['user', '-created_at'], name='ai_usage_user_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('date', models.DateField()),
                ('im_count', models.PositiveIntegerField(default=0)),
                ('meeting_count', models.PositiveIntegerField(default=0)),
                ('calendar_count', models.PositiveIntegerField(default=0)),
                ('docs_count', models.PositiveIntegerField(default=0)),
                ('approval_count', models.PositiveIntegerField(default=0)),
                ('ai_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User daily activity',
                'verbose_name_plural': 'User daily activity',
                'db_table': 'meet_user_daily_activity',
                'ordering': ('-date',),
                'indexes': [models.Index(fields=['organization', '-date'], name='activity_org_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='user_daily_activity_unique')],
            },
        ),
    ]
