# Generated by Django 5.2.14 on 2026-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_backfill_room_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orginvitation',
            name='one_pending_invite_per_email_org',
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='orginvitation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='orginvitation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email'),
        ),
        migrations.AddConstraint(
            model_name='orginvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('email', ''), _negated=True)), fields=('organization', 'email'), name='one_pending_invite_per_email_org', violation_error_message='A pending invitation already exists for this email.'),
        ),
        migrations.AddConstraint(
            model_name='orginvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('phone', ''), _negated=True)), fields=('organization', 'phone'), name='one_pending_invite_per_phone_org', violation_error_message='A pending invitation already exists for this phone number.'),
        ),
        migrations.AddConstraint(
            model_name='orginvitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('phone', ''), _negated=True), _connector='OR'), name='invitation_has_email_or_phone', violation_error_message='An invitation needs an email address or a phone number.'),
        ),
    ]
