# Generated by Django 5.2.14 on 2026-08-02 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_invitation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('role.create', 'Admin role created'), ('role.update', 'Admin role updated'), ('role.delete', 'Admin role deleted'), ('role.assign', 'Admin role assigned'), ('role.unassign', 'Admin role revoked'), ('member.import', 'Members imported'), ('member.export', 'Members exported'), ('invite_link.create', 'Invite link created'), ('invite_link.revoke', 'Invite link revoked'), ('join_request.approve', 'Join request approved'), ('join_request.reject', 'Join request rejected'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='OrgInviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('code', models.CharField(db_index=True, editable=False, max_length=16, unique=True, verbose_name='code')),
                ('org_role', models.CharField(choices=[('member', 'Member'), ('dept_admin', 'Department administrator'), ('administrator', 'Organization administrator'), ('owner', 'Organization owner')], default='member', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('require_approval', models.BooleanField(default=True, verbose_name='require approval')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Null means unlimited.', null=True, verbose_name='max uses')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_links', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department applicants land in (null = organization level).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='core.organization')),
            ],
            options={
                'verbose_name': 'Organization invite link',
                'verbose_name_plural': 'Organization invite links',
                'db_table': 'meet_org_invite_link',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrgJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='phone')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='full name')),
                ('org_role', models.CharField(choices=[('member', 'Member'), ('dept_admin', 'Department administrator'), ('administrator', 'Organization administrator'), ('owner', 'Organization owner')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='core.department')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='core.orginvitelink')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization join request',
                'verbose_name_plural': 'Organization join requests',
                'db_table': 'meet_org_join_request',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='orginvitelink',
            index=models.Index(fields=['organization', 'is_active'], name='invite_link_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='orginvitelink',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('max_uses__gt', 0), _connector='OR'), name='invite_link_max_uses_positive', violation_error_message='Max uses must be greater than zero.'),
        ),
        migrations.AddIndex(
            model_name='orgjoinrequest',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='join_request_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='orgjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user'), name='one_pending_join_request', violation_error_message='You already have a pending application for this organization.'),
        ),
    ]
