# Generated by Django 5.2.14 on 2026-08-04 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_invite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('role.create', 'Admin role created'), ('role.update', 'Admin role updated'), ('role.delete', 'Admin role deleted'), ('role.assign', 'Admin role assigned'), ('role.unassign', 'Admin role revoked'), ('member.import', 'Members imported'), ('member.export', 'Members exported'), ('invite_link.create', 'Invite link created'), ('invite_link.revoke', 'Invite link revoked'), ('join_request.approve', 'Join request approved'), ('join_request.reject', 'Join request rejected'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted'), ('bot.create', 'Group bot created'), ('bot.update', 'Group bot updated'), ('bot.delete', 'Group bot removed'), ('bot.secret_reset', 'Group bot credential rotated'), ('bot.webhook_view', 'Group bot webhook address viewed')], max_length=40),
        ),
        migrations.CreateModel(
            name='ImBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('kind', models.CharField(choices=[('custom', 'Custom webhook bot'), ('builtin', 'Built-in assistant')], default='custom', max_length=16, verbose_name='kind')),
                ('slug', models.SlugField(blank=True, default='', max_length=64, verbose_name='slug')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('description', models.CharField(blank=True, default='', help_text='Shown next to the name on every message this bot sends.', max_length=256, verbose_name='description')),
                ('avatar_key', models.CharField(blank=True, default='', max_length=500, verbose_name='avatar object key')),
                ('avatar_color_index', models.PositiveSmallIntegerField(default=0, help_text='Index into the shared bot palette; used to re-render the swatch.', verbose_name='avatar colour')),
                ('im_uid', models.CharField(blank=True, editable=False, max_length=36, null=True, unique=True, verbose_name='IM uid')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_im_bots', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='im_bots', to='core.organization')),
            ],
            options={
                'verbose_name': 'IM bot',
                'verbose_name_plural': 'IM bots',
                'db_table': 'meet_im_bot',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImBotInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('cid', models.CharField(db_index=True, max_length=64, verbose_name='conversation id')),
                ('webhook_token', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='webhook token')),
                ('signing_secret', models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='signing secret')),
                ('sign_verify_enabled', models.BooleanField(default=False, verbose_name='verify signature')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Any one must appear in the message text. Empty = no keyword gate.', verbose_name='keywords')),
                ('ip_allowlist', models.JSONField(blank=True, default=list, help_text='IPs or CIDRs allowed to post. Empty = no IP gate.', verbose_name='IP allowlist')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=32, verbose_name='disabled reason')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='messages sent')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='core.imbot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_im_bot_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IM bot installation',
                'verbose_name_plural': 'IM bot installations',
                'db_table': 'meet_im_bot_installation',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='imbot',
            index=models.Index(fields=['im_uid'], name='im_bot_uid_idx'),
        ),
        migrations.AddConstraint(
            model_name='imbot',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'builtin')), fields=('slug',), name='one_bot_per_builtin_slug'),
        ),
        migrations.AddConstraint(
            model_name='imbotinstallation',
            constraint=models.UniqueConstraint(fields=('bot', 'cid'), name='one_installation_per_bot_conversation'),
        ),
    ]
