# Generated by Django 5.2.14 on 2026-08-05 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_seed_builtin_bots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImCardMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('mid', models.BigIntegerField(unique=True, verbose_name='jusi message id')),
                ('cid', models.CharField(db_index=True, max_length=64, verbose_name='conversation id')),
                ('buttons', models.JSONField(blank=True, default=dict, verbose_name='button definitions')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='button values')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_messages', to='core.imbotinstallation')),
            ],
            options={
                'verbose_name': 'IM card message',
                'verbose_name_plural': 'IM card messages',
                'db_table': 'meet_im_card_message',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImCardAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('block', models.CharField(max_length=16, verbose_name='actions block')),
                ('button_id', models.CharField(max_length=32, verbose_name='button id')),
                ('resolves', models.BooleanField(default=False, verbose_name='resolves the block')),
                ('click_id', models.CharField(blank=True, default='', max_length=64, verbose_name='client click id')),
                ('result_text', models.CharField(blank=True, default='', max_length=200, verbose_name='result text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_card_actions', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.imcardmessage')),
            ],
            options={
                'verbose_name': 'IM card action',
                'verbose_name_plural': 'IM card actions',
                'db_table': 'meet_im_card_action',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['card', 'block'], name='meet_im_car_card_id_990115_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolves', True)), fields=('card', 'block'), name='one_resolution_per_actions_block'), models.UniqueConstraint(condition=models.Q(('click_id', ''), _negated=True), fields=('card', 'user', 'click_id'), name='card_click_id_is_idempotent')],
            },
        ),
    ]
