# Generated by Django 5.2.14 on 2026-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_im_card_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='imbotinstallation',
            name='callback_enabled',
            field=models.BooleanField(default=True, verbose_name='callback enabled'),
        ),
        migrations.AddField(
            model_name='imbotinstallation',
            name='callback_failure_count',
            field=models.PositiveIntegerField(default=0, verbose_name='consecutive callback failures'),
        ),
        migrations.AddField(
            model_name='imbotinstallation',
            name='callback_include_identity',
            field=models.BooleanField(default=False, verbose_name='send clicker name'),
        ),
        migrations.AddField(
            model_name='imbotinstallation',
            name='callback_secret',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='callback secret'),
        ),
        migrations.AddField(
            model_name='imbotinstallation',
            name='callback_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='callback url'),
        ),
        migrations.AddField(
            model_name='imcardaction',
            name='callback_error',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='callback error category'),
        ),
        migrations.AddField(
            model_name='imcardaction',
            name='callback_state',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='callback state'),
        ),
    ]
