# Generated by Django 5.2.14 on 2026-08-05 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_from_installations(apps, schema_editor):
    """给已经装了机器人的会话建投影行,组织从建机器人的人推出来。

    影响面基本为零 —— 机器人 2026-08-04 才上线,这也正是「不改 jusi、走本地
    投影」现在成本最低的时点:再晚一个月,存量会话就得靠人去对了。

    **名字留空**:jusi 没有 admin 读接口,这里无从得知群名。前端对空名显示
    「未命名群聊」+ 可复制的 cid 前 12 位,运营拿这串能去 IM 侧对上。下一次
    有人改群名时,写路径会把名字补上。
    """
    ImBotInstallation = apps.get_model("core", "ImBotInstallation")
    ImConversation = apps.get_model("core", "ImConversation")

    seen = set(ImConversation.objects.values_list("cid", flat=True))
    rows = []
    for cid, organization_id, created_by_id in (
        ImBotInstallation.objects.exclude(cid="")
        .order_by("created_at")
        .values_list("cid", "bot__organization_id", "created_by_id")
    ):
        if cid in seen:
            continue
        seen.add(cid)
        rows.append(
            ImConversation(
                cid=cid, organization_id=organization_id, created_by_id=created_by_id
            )
        )
    ImConversation.objects.bulk_create(rows, batch_size=500)


def drop_backfilled(apps, schema_editor):
    """回滚方向留空:表整个会被 CreateModel 的反向操作删掉。"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_bot_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('cid', models.CharField(max_length=64, unique=True, verbose_name='conversation id')),
                ('name', models.CharField(blank=True, default='', max_length=120, verbose_name='group name')),
            ],
            options={
                'verbose_name': 'IM conversation',
                'verbose_name_plural': 'IM conversations',
                'db_table': 'meet_im_conversation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='imbotinstallation',
            index=models.Index(models.OrderBy(models.F('last_used_at'), descending=True, nulls_last=True), name='im_install_last_used_idx'),
        ),
        migrations.AddIndex(
            model_name='imbotinstallation',
            index=models.Index(fields=['bot', '-created_at'], name='im_install_bot_idx'),
        ),
        migrations.AddField(
            model_name='imconversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_im_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imconversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='im_conversations', to='core.organization'),
        ),
        migrations.RunPython(
            backfill_from_installations, drop_backfilled, elidable=True
        ),
    ]
