# Generated by Django 5.2.14 on 2026-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_im_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('dept.create', 'Department created'), ('dept.rename', 'Department renamed'), ('dept.update', 'Department updated'), ('dept.move', 'Department moved'), ('dept.delete', 'Department deleted'), ('member.add', 'Member added'), ('member.invite', 'Member invited'), ('member.invite_revoke', 'Member invitation revoked'), ('member.update', 'Member updated'), ('member.role_change', 'Member role changed'), ('member.department_change', 'Member department changed'), ('member.suspend', 'Member suspended'), ('member.restore', 'Member restored'), ('member.remove', 'Member removed'), ('member.offboard', 'Member offboarded'), ('member.rehire', 'Member rehired'), ('member.purge', 'Member record purged'), ('member.bulk_update', 'Members updated in bulk'), ('dict_item.create', 'Dictionary option created'), ('dict_item.update', 'Dictionary option updated'), ('dict_item.delete', 'Dictionary option deleted'), ('group.create', 'User group created'), ('group.update', 'User group updated'), ('group.delete', 'User group deleted'), ('group.member_add', 'User group members added'), ('group.member_remove', 'User group member removed'), ('role.create', 'Admin role created'), ('role.update', 'Admin role updated'), ('role.delete', 'Admin role deleted'), ('role.assign', 'Admin role assigned'), ('role.unassign', 'Admin role revoked'), ('member.import', 'Members imported'), ('member.export', 'Members exported'), ('invite_link.create', 'Invite link created'), ('invite_link.revoke', 'Invite link revoked'), ('join_request.approve', 'Join request approved'), ('join_request.reject', 'Join request rejected'), ('summary.edit', 'Meeting summary edited'), ('room_node.create', 'Room hierarchy node created'), ('room_node.update', 'Room hierarchy node updated'), ('room_node.move', 'Room hierarchy node moved'), ('room_node.delete', 'Room hierarchy node deleted'), ('meeting_room.create', 'Meeting room created'), ('meeting_room.update', 'Meeting room updated'), ('meeting_room.delete', 'Meeting room deleted'), ('meeting_room_facility.create', 'Meeting room facility created'), ('meeting_room_facility.update', 'Meeting room facility updated'), ('meeting_room_facility.delete', 'Meeting room facility deleted'), ('bot.create', 'Group bot created'), ('bot.update', 'Group bot updated'), ('bot.delete', 'Group bot removed'), ('bot.secret_reset', 'Group bot credential rotated'), ('bot.webhook_view', 'Group bot webhook address viewed'), ('bot.disable', 'Group bot disabled'), ('bot.enable', 'Group bot enabled')], max_length=40),
        ),
    ]
