# Generated by Django 5.2.14 on 2026-08-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_bot_governance_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_outcome',
            field=models.CharField(blank=True, default='', help_text='How the reminder ended: delivered / no_conversation / refused. Empty for events handled before this field existed.', max_length=24, verbose_name='reminder outcome'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reminder_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Idempotency guard: set once the reminder has been handled. Handled is not the same as delivered — see reminder_outcome.', null=True, verbose_name='reminder pushed at'),
        ),
    ]
