# Generated by Django 5.2.14 on 2026-08-11 00:57

from django.db import migrations, models


def unique_room_code(existing_code, name, room_id, used_codes):
    base = (existing_code or "").strip() or (name or "").strip()
    if not base:
        base = f"ROOM-{str(room_id)[:8].upper()}"
    base = base[:64]

    candidate = base
    suffix_number = 2
    while candidate in used_codes:
        suffix = f"-{suffix_number}"
        candidate = f"{base[: 64 - len(suffix)]}{suffix}"
        suffix_number += 1
    return candidate


def fill_missing_room_codes(apps, schema_editor):
    MeetingRoom = apps.get_model("core", "MeetingRoom")
    used_codes_by_node = {}

    # Preserve active-room identifiers first. Deleted rows still need a non-blank
    # code for the new check constraint, but must never force an active room to
    # acquire a synthetic suffix merely because an old deleted row used it.
    for deleted in (False, True):
        rooms = MeetingRoom.objects.filter(deleted_at__isnull=not deleted).order_by(
            "node_id", "created_at", "id"
        )
        for room in rooms:
            used_codes = used_codes_by_node.setdefault(room.node_id, set())
            candidate = unique_room_code(room.code, room.name, room.id, used_codes)
            used_codes.add(candidate)
            if room.code != candidate:
                MeetingRoom.objects.filter(pk=room.pk).update(code=candidate)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_meeting_room_floor_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingroom",
            options={
                "ordering": ("sort_order", "code", "name"),
                "verbose_name": "Meeting room",
                "verbose_name_plural": "Meeting rooms",
            },
        ),
        migrations.RemoveConstraint(
            model_name="meetingroom",
            name="mroom_uniq_org_code",
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="name"
            ),
        ),
        migrations.RunPython(fill_missing_room_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="meetingroom",
            name="code",
            field=models.CharField(max_length=64, verbose_name="code"),
        ),
        migrations.AddConstraint(
            model_name="meetingroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("node", "code"),
                name="mroom_uniq_node_code",
                violation_error_message="A room with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingroom",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="mroom_code_not_blank",
                violation_error_message="Room code is required.",
            ),
        ),
    ]
