# Generated by Django 5.2.14 on 2026-08-11 00:57

from django.db import migrations, models


def fill_missing_room_codes(apps, schema_editor):
    MeetingRoom = apps.get_model("core", "MeetingRoom")
    used_codes_by_node = {}

    for room in MeetingRoom.objects.order_by("node_id", "created_at", "id"):
        used_codes = used_codes_by_node.setdefault(room.node_id, set())
        existing_code = (room.code or "").strip()
        base = existing_code or (room.name or "").strip()
        if not base:
            base = f"ROOM-{str(room.id)[:8].upper()}"
        base = base[:64]

        candidate = base
        suffix_number = 2
        while candidate in used_codes:
            suffix = f"-{suffix_number}"
            candidate = f"{base[: 64 - len(suffix)]}{suffix}"
            suffix_number += 1

        used_codes.add(candidate)
        if room.code != candidate:
            MeetingRoom.objects.filter(pk=room.pk).update(code=candidate)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_meeting_room_floor_attribute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingroom",
            options={
                "ordering": ("sort_order", "code", "name"),
                "verbose_name": "Meeting room",
                "verbose_name_plural": "Meeting rooms",
            },
        ),
        migrations.RemoveConstraint(
            model_name="meetingroom",
            name="mroom_uniq_org_code",
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="name"
            ),
        ),
        migrations.RunPython(fill_missing_room_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="meetingroom",
            name="code",
            field=models.CharField(max_length=64, verbose_name="code"),
        ),
        migrations.AddConstraint(
            model_name="meetingroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("node", "code"),
                name="mroom_uniq_node_code",
                violation_error_message="A room with this code already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingroom",
            constraint=models.CheckConstraint(
                condition=models.Q(("code", ""), _negated=True),
                name="mroom_code_not_blank",
                violation_error_message="Room code is required.",
            ),
        ),
    ]
