# Generated by Django 5.2.14 on 2026-08-13 03:11

import uuid

import django.db.models.deletion
from django.db import migrations, models

import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_unified_calendars_exports_external_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='calendar name'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='organization_default_access',
            field=models.CharField(choices=[('none', 'Not shared'), ('free_busy', 'Free/busy only'), ('details', 'Event details'), ('writer', 'Can edit events'), ('admin', 'Calendar administrator')], default='free_busy', help_text='Access inherited by active members of this organization unless an explicit grant overrides it.', max_length=16),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='attachment_names',
            field=models.JSONField(blank=True, default=list, verbose_name='attachment names'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source_calendar',
            field=models.ForeignKey(blank=True, help_text="Owning calendar. Null is accepted only for legacy writers and is filled with the organizer's primary calendar by the API.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_events', to='core.calendar'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='sync_status',
            field=models.CharField(blank=True, default='', help_text='External provider state: pending/synced/conflict/error.', max_length=24),
        ),
        migrations.AlterField(
            model_name='calendarexportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='calendarexportjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='calendarexportjob',
            name='range_end',
            field=models.DateField(help_text='Inclusive civil end date in the export timezone.'),
        ),
        migrations.AlterField(
            model_name='calendarexportjob',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='UTC', use_pytz=False),
        ),
        migrations.AlterField(
            model_name='calendarexportjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='calendarsyncoutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='calendarsyncoutbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='calendarsyncoutbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='externalcalendaraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='externalcalendaraccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='externalcalendaraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='externalcalendarbinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='externalcalendarbinding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='externalcalendarbinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='externaleventmirror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='externaleventmirror',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='externaleventmirror',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on'),
        ),
    ]
