# Generated by Django 5.2.14 on 2026-08-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_meeting_session_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Concrete meeting lifecycle that produced this recording. "
                    "Null is retained only for legacy or unresolved writes during rollout."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordings",
                to="core.meetingsession",
                verbose_name="meeting session",
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="ingest_id",
            field=models.UUIDField(
                blank=True,
                help_text="Agent-generated idempotency key for transcript retries.",
                null=True,
                unique=True,
                verbose_name="ingest id",
            ),
        ),
        migrations.AddField(
            model_name="transcript",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Concrete meeting lifecycle that produced this transcript. "
                    "Null is retained only for legacy or unresolved writes during rollout."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcripts",
                to="core.meetingsession",
                verbose_name="meeting session",
            ),
        ),
        migrations.AddIndex(
            model_name="recording",
            index=models.Index(
                fields=["session", "-created_at"],
                name="meet_rec_session_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["session", "started_at"],
                name="meet_tr_session_start_idx",
            ),
        ),
    ]
