# Generated by Django 5.2.14 on 2026-08-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_recording_session_transcript_ingest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingdoc',
            name='session',
            field=models.OneToOneField(blank=True, help_text='the concrete meeting session this document was created from; null is retained for legacy documents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_doc', to='core.meetingsession'),
        ),
        migrations.AddField(
            model_name='summary',
            name='im_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Set after this session summary is posted to the Room IM group.', null=True, verbose_name='IM pushed at'),
        ),
        migrations.AddField(
            model_name='summary',
            name='session',
            field=models.OneToOneField(blank=True, help_text='Concrete meeting lifecycle summarized by this row. Null is retained only for legacy summaries until historical backfill.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.meetingsession', verbose_name='meeting session'),
        ),
        migrations.AddField(
            model_name='transcriptchunk',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Concrete meeting lifecycle indexed by this chunk. Null is retained only for legacy chunks until historical backfill.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.meetingsession', verbose_name='meeting session'),
        ),
        migrations.AlterField(
            model_name='meetingdoc',
            name='room',
            field=models.ForeignKey(blank=True, help_text='the meeting room this document was created for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_docs', to='core.room'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.room', verbose_name='room'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['room', '-updated_at'], name='meet_sum_room_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptchunk',
            index=models.Index(fields=['session', 'chunk_index'], name='meet_chunk_session_idx'),
        ),
    ]
