# Generated by Django 5.2.14 on 2026-08-18 02:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0101_meetingdoc_session_summary_im_pushed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="im_pushed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set after all intended IM deliveries for this summary succeed.",
                null=True,
                verbose_name="IM pushed at",
            ),
        ),
        migrations.CreateModel(
            name="SummaryImDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="conversation id",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="delivered at",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="last error"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_summary_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_deliveries",
                        to="core.summary",
                        verbose_name="meeting summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting summary IM delivery",
                "verbose_name_plural": "meeting summary IM deliveries",
                "db_table": "meet_summary_im_delivery",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("summary", "recipient"),
                        name="uniq_summary_im_delivery_recipient",
                    )
                ],
            },
        ),
    ]
