# Generated by Django 5.2.14 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_action_item_lifecycle(apps, schema_editor):
    ActionItem = apps.get_model("core", "ActionItem")
    ActionItem.objects.filter(is_completed=True).update(
        status="completed",
        confirmed_at=models.F("updated_at"),
        completed_at=models.F("updated_at"),
    )

    summaries = {
        summary_id: session_id
        for summary_id, session_id in apps.get_model("core", "Summary")
        .objects.exclude(session_id=None)
        .values_list("id", "session_id")
    }
    for summary_id, session_id in summaries.items():
        ActionItem.objects.filter(
            summary_id=summary_id, session_id=None
        ).update(session_id=session_id)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_alter_summary_im_pushed_at_summaryimdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_meeting_action_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="completed at"
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmed at"
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_meeting_action_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="confirmed by",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="due_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="due at"
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_items",
                to="core.meetingsession",
                verbose_name="meeting session",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("dismissed", "Dismissed"),
                ],
                db_index=True,
                default="proposed",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="actionitem",
            name="task_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Reserved link to the task created from this action item.",
                null=True,
                verbose_name="linked task id",
            ),
        ),
        migrations.RunPython(
            backfill_action_item_lifecycle,
            migrations.RunPython.noop,
        ),
    ]
