# Generated by Django 5.2.14 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_task_foundation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="due_at",
            new_name="due_date",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="due date",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("status", "due_date", "created_at"),
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
