# Generated by Django 5.2.5 on 2026-08-20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_task_dates"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskImDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("reassigned", "Reassigned"),
                        ],
                        max_length=16,
                        verbose_name="event",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="conversation id",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="attempt count"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="next attempt at",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="delivered at",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, default="", verbose_name="last error"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_im_deliveries",
                        to="core.user",
                        verbose_name="recipient",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_deliveries",
                        to="core.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task IM delivery",
                "verbose_name_plural": "task IM deliveries",
                "db_table": "meet_task_im_delivery",
                "ordering": ("created_at",),
            },
        ),
    ]
