# Generated by Django 5.2.5 on 2026-08-20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_taskimdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("content_changed", "Content changed"),
                            ("dates_changed", "Dates changed"),
                            ("assignee_changed", "Assignee changed"),
                            ("status_changed", "Status changed"),
                        ],
                        max_length=32,
                        verbose_name="event",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="changes"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_activities",
                        to="core.user",
                        verbose_name="actor",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task activity",
                "verbose_name_plural": "task activities",
                "db_table": "meet_task_activity",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"],
                        name="task_act_task_created_idx",
                    )
                ],
            },
        ),
    ]
