# Generated by Django 5.2.5 on 2026-08-20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_taskactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_comments",
                        to="core.user",
                        verbose_name="author",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task comment",
                "verbose_name_plural": "task comments",
                "db_table": "meet_task_comment",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_comment_created_idx",
                    )
                ],
            },
        ),
    ]
