# Generated by Django 5.2.5 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_seed_task_assistant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskimdelivery",
            name="event",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("commented", "Commented"),
                ],
                max_length=16,
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="taskimdelivery",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="im_deliveries",
                to="core.taskcomment",
                verbose_name="comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskimdelivery",
            constraint=models.UniqueConstraint(
                fields=("comment", "recipient"),
                name="task_im_comment_recipient_uniq",
            ),
        ),
    ]
