# Generated by Django 5.2.5 on 2026-08-21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_task_comment_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[
                    ("background_image", "Background image"),
                    ("task_attachment", "Task attachment"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attachment",
                        to="core.file",
                        verbose_name="file",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_attachments",
                        to="core.user",
                        verbose_name="uploader",
                    ),
                ),
            ],
            options={
                "verbose_name": "task attachment",
                "verbose_name_plural": "task attachments",
                "db_table": "meet_task_attachment",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["task", "created_at"],
                        name="task_attach_created_idx",
                    )
                ],
            },
        ),
    ]
