# Generated by Django 5.2.5 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0112_task_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="storage_bucket",
            field=models.CharField(blank=True, default="", editable=False, max_length=63),
        ),
    ]
