# Generated by Django 5.2.5 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0113_file_storage_bucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskactivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_changed", "Content changed"),
                    ("dates_changed", "Dates changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("status_changed", "Status changed"),
                    ("attachment_removed", "Attachment removed"),
                ],
                max_length=32,
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="taskimdelivery",
            name="event",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("commented", "Commented"),
                    ("starting", "Starting"),
                    ("due_today", "Due today"),
                    ("overdue", "Overdue"),
                ],
                max_length=16,
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="taskimdelivery",
            name="reference_date",
            field=models.DateField(
                blank=True,
                help_text="Task date used as the idempotency key for reminder events.",
                null=True,
                verbose_name="reference date",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskimdelivery",
            constraint=models.UniqueConstraint(
                fields=("task", "recipient", "event", "reference_date"),
                name="task_im_reminder_reference_uniq",
            ),
        ),
    ]
