# Generated by Django 5.2.5 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0114_task_time_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskimdelivery",
            name="event",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("commented", "Commented"),
                    ("dates_changed", "Dates changed"),
                    ("starting", "Starting"),
                    ("due_today", "Due today"),
                    ("overdue", "Overdue"),
                ],
                max_length=16,
                verbose_name="event",
            ),
        ),
        migrations.AddField(
            model_name="taskimdelivery",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="im_deliveries",
                to="core.taskactivity",
                verbose_name="activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskimdelivery",
            constraint=models.UniqueConstraint(
                fields=("activity", "recipient"),
                name="task_im_activity_recipient_uniq",
            ),
        ),
    ]
