# Generated by Django 5.2.5 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0115_task_date_change_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskimdelivery",
            name="event",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("commented", "Commented"),
                    ("dates_changed", "Dates changed"),
                    ("status_changed", "Status changed"),
                    ("starting", "Starting"),
                    ("due_today", "Due today"),
                    ("overdue", "Overdue"),
                ],
                max_length=16,
                verbose_name="event",
            ),
        ),
    ]
