# Generated by Django 5.2.5 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_task_status_change_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionitem",
            name="task_status_sync_activity",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text=(
                    "Latest task activity that changed this action item's status; "
                    "cleared by a manual status override."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_action_items",
                to="core.taskactivity",
                verbose_name="task status sync activity",
            ),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_changed", "Content changed"),
                    ("dates_changed", "Dates changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("status_changed", "Status changed"),
                    ("attachment_removed", "Attachment removed"),
                    ("source_action_item_changed", "Source action item changed"),
                ],
                max_length=32,
                verbose_name="event",
            ),
        ),
    ]
