# Generated by Django 5.2.5 on 2026-08-21

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_task_organizations(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    Membership = apps.get_model("core", "Membership")

    organization_id = (
        Membership.objects.filter(
            user_id=OuterRef("creator_id"),
            status="active",
        )
        .order_by("-is_primary", "created_at")
        .values("organization_id")[:1]
    )
    Task.objects.filter(organization_id__isnull=True).update(
        organization_id=Subquery(organization_id)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_task_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        editable=False,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="name")),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("grey", "Grey"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                        ],
                        default="grey",
                        max_length=16,
                        verbose_name="color",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_labels",
                        to="core.user",
                        verbose_name="creator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_labels",
                        to="core.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "task label",
                "verbose_name_plural": "task labels",
                "db_table": "meet_task_label",
                "ordering": ("name", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="tasklabel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="task_label_name_ci_unique_org",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.RunPython(
            backfill_task_organizations,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                to="core.tasklabel",
                verbose_name="labels",
            ),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_changed", "Content changed"),
                    ("dates_changed", "Dates changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("labels_changed", "Labels changed"),
                    ("attachment_removed", "Attachment removed"),
                    ("source_action_item_changed", "Source action item changed"),
                ],
                max_length=32,
                verbose_name="event",
            ),
        ),
    ]
