# Generated by Django 5.2.5 on 2026-08-22

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0119_task_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        editable=False,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="description"),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("grey", "Grey"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                            ("purple", "Purple"),
                        ],
                        default="blue",
                        max_length=16,
                        verbose_name="color",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False, verbose_name="archived")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_lists",
                        to="core.user",
                        verbose_name="creator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_lists",
                        to="core.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "task list",
                "verbose_name_plural": "task lists",
                "db_table": "meet_task_list",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="TaskGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        editable=False,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="sort order")),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="core.tasklist",
                        verbose_name="task list",
                    ),
                ),
            ],
            options={
                "verbose_name": "task group",
                "verbose_name_plural": "task groups",
                "db_table": "meet_task_group",
                "ordering": ("sort_order", "created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="tasklist",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="task_list_name_ci_unique_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskgroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("task_list"),
                name="task_group_name_ci_unique_list",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.taskgroup",
                verbose_name="task group",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
        migrations.AddField(
            model_name="task",
            name="task_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="core.tasklist",
                verbose_name="task list",
            ),
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_changed", "Content changed"),
                    ("dates_changed", "Dates changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("labels_changed", "Labels changed"),
                    ("placement_changed", "Placement changed"),
                    ("attachment_removed", "Attachment removed"),
                    ("source_action_item_changed", "Source action item changed"),
                ],
                max_length=32,
                verbose_name="event",
            ),
        ),
    ]
