# Generated by Django 5.2.5 on 2026-08-22

from django.db import migrations, models


def delete_label_activities(apps, _schema_editor):
    task_activity = apps.get_model("core", "TaskActivity")
    task_activity.objects.filter(event="labels_changed").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0120_task_lists_groups_statistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="labels",
        ),
        migrations.DeleteModel(
            name="TaskLabel",
        ),
        migrations.RunPython(
            delete_label_activities,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="taskactivity",
            name="event",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("content_changed", "Content changed"),
                    ("dates_changed", "Dates changed"),
                    ("assignee_changed", "Assignee changed"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("placement_changed", "Placement changed"),
                    ("attachment_removed", "Attachment removed"),
                    ("source_action_item_changed", "Source action item changed"),
                ],
                max_length=32,
                verbose_name="event",
            ),
        ),
    ]
