# Generated by Django 5.2.14 on 2026-08-24

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0121_remove_task_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskListGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        editable=False,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="sort order"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_list_groups",
                        to="core.user",
                        verbose_name="creator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_list_groups",
                        to="core.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "task list group",
                "verbose_name_plural": "task list groups",
                "db_table": "meet_task_list_group",
                "ordering": ("sort_order", "created_at", "id"),
            },
        ),
        migrations.AddField(
            model_name="tasklist",
            name="list_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_lists",
                to="core.tasklistgroup",
                verbose_name="task list group",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasklistgroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="task_list_group_name_ci_unique_org",
            ),
        ),
    ]
