# Generated by Django 5.2.14 on 2026-08-27 05:16

import django.db.models.deletion
import timezone_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_taskactivity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_key',
            field=models.DateField(blank=True, null=True, verbose_name='recurrence key'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_sequence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='recurrence sequence'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('content_changed', 'Content changed'), ('dates_changed', 'Dates changed'), ('assignee_changed', 'Assignee changed'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('placement_changed', 'Placement changed'), ('hierarchy_changed', 'Hierarchy changed'), ('recurrence_changed', 'Recurrence changed'), ('attachment_removed', 'Attachment removed'), ('source_action_item_changed', 'Source action item changed')], max_length=32, verbose_name='event'),
        ),
        migrations.CreateModel(
            name='TaskRecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=16, verbose_name='frequency')),
                ('interval', models.PositiveSmallIntegerField(default=1, verbose_name='interval')),
                ('timezone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='UTC', help_text='Timezone captured from the rule owner.', use_pytz=False)),
                ('schedule_anchor_date', models.DateField(verbose_name='schedule anchor date')),
                ('anchor_day', models.PositiveSmallIntegerField(verbose_name='anchor day')),
                ('anchor_is_month_end', models.BooleanField(default=False, verbose_name='anchor is month end')),
                ('next_occurrence_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='next occurrence date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('max_occurrences', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='maximum occurrences')),
                ('generated_count', models.PositiveSmallIntegerField(default=1, verbose_name='generated count')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('last_error', models.CharField(blank=True, default='', max_length=64, verbose_name='last error')),
                ('template_title', models.TextField(verbose_name='template title')),
                ('template_description', models.TextField(blank=True, default='', verbose_name='template description')),
                ('template_priority', models.CharField(choices=[('none', 'No priority'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16, verbose_name='template priority')),
                ('template_start_offset_days', models.IntegerField(blank=True, null=True, verbose_name='template start offset days')),
                ('template_due_offset_days', models.IntegerField(blank=True, null=True, verbose_name='template due offset days')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_task_recurrence_rules', to=settings.AUTH_USER_MODEL, verbose_name='assignees')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_task_recurrence_rules', to=settings.AUTH_USER_MODEL, verbose_name='followers')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules', to='core.taskgroup', verbose_name='task group')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_recurrence_rules', to='core.organization', verbose_name='organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_recurrence_rules', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('task_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules', to='core.tasklist', verbose_name='task list')),
                ('template_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_task_recurrence_rules', to=settings.AUTH_USER_MODEL, verbose_name='template assignee')),
            ],
            options={
                'verbose_name': 'task recurrence rule',
                'verbose_name_plural': 'task recurrence rules',
                'db_table': 'meet_task_recurrence_rule',
                'ordering': ('next_occurrence_date', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='core.taskrecurrencerule', verbose_name='recurrence rule'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence_key__isnull', False), ('recurrence_rule__isnull', False)), fields=('recurrence_rule', 'recurrence_key'), name='task_recurrence_cycle_uniq'),
        ),
        migrations.AddIndex(
            model_name='taskrecurrencerule',
            index=models.Index(fields=['is_active', 'next_occurrence_date'], name='task_recur_due_idx'),
        ),
    ]
