# Generated by Django 5.2.14 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0140_task_message_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="imconversation",
            name="avatar_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="group avatar object key",
            ),
        ),
    ]
