# Generated by Django 5.2.14 on 2026-09-11 13:19

"""只改 ``full_name_initial`` 的 help_text(去掉对已删除的 alphabet 端点的引用)。

数据库层面是空操作(help_text 不进 DB),但 Django 把 help_text 算进模型状态,不改就
过不了 ``makemigrations --check``。这是删除 `?from_initial=` / `alphabet/` 之后的
收尾:字段本身、``initial`` 序列化字段与墓碑卡全都还在,只是注释里的旧指向没了。
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_user_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name_initial',
            field=models.CharField(blank=True, default='#', help_text="A–Z initial of `full name` (derived on save); '#' for names whose initial cannot be derived (digits, symbols, empty). Clients use it for the sticky letter header in the directory list.", max_length=1, verbose_name='full name initial'),
        ),
    ]
