# Generated by Django 5.2.11 on 2026-09-12 14:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_task_list_ownership_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('device_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('recording', 'Recording'), ('paused', 'Paused'), ('interrupted', 'Interrupted'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='preparing', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('captured_duration_ms', models.PositiveBigIntegerField(default=0)),
                ('last_acked_sequence', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meet_capture_session',
            },
        ),
        migrations.CreateModel(
            name='MeetingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('source_type', models.CharField(choices=[('meeting', 'Meeting'), ('audio_recording', 'Audio recording'), ('upload', 'Upload')], max_length=20)),
                ('source_session_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('origin_at', models.DateTimeField()),
                ('retention_mode', models.CharField(choices=[('media', 'Keep media'), ('text', 'Keep text only'), ('unknown', 'Legacy retention unknown')], default='unknown', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('meeting_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='core.meetingsession')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_records', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meet_meeting_record',
                'ordering': ('-origin_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MeetingProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('kind', models.CharField(choices=[('transcription', 'Transcription'), ('summary', 'Summary'), ('doc', 'Document'), ('delivery', 'Delivery')], max_length=16)),
                ('generation', models.PositiveIntegerField()),
                ('input_revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('retryable', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='core.meetingrecord')),
            ],
            options={
                'db_table': 'meet_meeting_processing_job',
            },
        ),
        migrations.CreateModel(
            name='MeetingMediaSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sequence', models.PositiveIntegerField()),
                ('record_start_ms', models.PositiveBigIntegerField()),
                ('duration_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$')])),
                ('capture_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='core.capturesession')),
                ('recording', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_segment', to='core.recording')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_segments', to='core.meetingrecord')),
            ],
            options={
                'db_table': 'meet_meeting_media_segment',
                'ordering': ('record_start_ms', 'sequence'),
            },
        ),
        migrations.AddField(
            model_name='capturesession',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='core.meetingrecord'),
        ),
        migrations.CreateModel(
            name='MeetingRecordAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('read_summary', models.BooleanField(default=False)),
                ('read_transcript', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.meetingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meet_meeting_record_access',
            },
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_session_id__isnull', False), ('source_type', 'meeting')), models.Q(('meeting_session__isnull', True), ('source_session_id__isnull', True), ('source_type__in', ['audio_recording', 'upload'])), _connector='OR'), name='record_source_consistent'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('meeting_session__isnull', True), ('meeting_session_id', models.F('source_session_id')), _connector='OR'), name='record_session_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='record_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='meetingprocessingjob',
            constraint=models.UniqueConstraint(fields=('record', 'kind', 'generation'), name='unique_record_job_generation'),
        ),
        migrations.AddConstraint(
            model_name='meetingprocessingjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1), ('generation__gte', 1), ('input_revision__gte', 1)), name='job_positive_versions'),
        ),
        migrations.AddConstraint(
            model_name='meetingmediasegment',
            constraint=models.UniqueConstraint(fields=('record', 'sequence'), name='unique_record_media_sequence'),
        ),
        migrations.AddConstraint(
            model_name='meetingmediasegment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='media_positive_sequence'),
        ),
        migrations.AddConstraint(
            model_name='capturesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'stopped'), _negated=True), fields=('record',), name='unique_active_capture_record'),
        ),
        migrations.AddConstraint(
            model_name='capturesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'stopped'), _negated=True), fields=('created_by', 'device_id'), name='unique_active_capture_device'),
        ),
        migrations.AddConstraint(
            model_name='capturesession',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='capture_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='capturesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='capture_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='capturesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', False), ('status', 'stopped')), models.Q(models.Q(('status', 'stopped'), _negated=True), ('ended_at__isnull', True)), _connector='OR'), name='capture_end_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='meetingrecordaccess',
            constraint=models.UniqueConstraint(fields=('record', 'user'), name='unique_record_user_access'),
        ),
    ]
