# Generated by Django 5.2.14 on 2026-09-12 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_meeting_record_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingprocessingjob',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MeetingTranscriptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('revision', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('segments', models.JSONField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_versions', to='core.meetingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingSummaryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('stage', models.CharField(choices=[('final', 'Final')], default='final', max_length=16)),
                ('content', models.JSONField()),
                ('model_used', models.CharField(max_length=128)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='summary_version', to='core.meetingprocessingjob')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_versions', to='core.meetingrecord')),
                ('input_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='summaries', to='core.meetingtranscriptversion')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='meetingprocessingjob',
            name='input_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='jobs', to='core.meetingtranscriptversion'),
        ),
        migrations.AddConstraint(
            model_name='meetingtranscriptversion',
            constraint=models.UniqueConstraint(fields=('record', 'revision'), name='unique_record_transcript_revision'),
        ),
    ]
