# Generated by Django 5.2.14 on 2026-09-12 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_meeting_summary_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscriptversion',
            name='delivery',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TranscriptDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('state', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='open', max_length=16)),
                ('final_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_deliveries', to='core.meetingsession')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sequence', models.PositiveIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.transcriptdelivery')),
                ('transcript', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_receipt', to='core.transcript')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transcriptdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('final_sequence__isnull', True), ('state', 'open')), models.Q(('final_sequence__isnull', False), ('state__in', ['complete', 'incomplete'])), _connector='OR'), name='delivery_terminal_sequence'),
        ),
        migrations.AddConstraint(
            model_name='transcriptreceipt',
            constraint=models.UniqueConstraint(fields=('delivery', 'sequence'), name='unique_delivery_sequence'),
        ),
        migrations.AddConstraint(
            model_name='transcriptreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='delivery_sequence_positive'),
        ),
    ]
