# Generated by Django 5.2.14 on 2026-09-12 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_transcript_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummaryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('payload', models.JSONField()),
                ('attempt', models.PositiveIntegerField()),
                ('dispatch_state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('abandoned', 'Abandoned')], default='pending', max_length=16)),
                ('dispatch_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='core.meetingprocessingjob')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_requests', to='core.meetingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_summary_request')],
            },
        ),
    ]
