# Generated by Django 5.2.14 on 2026-09-12 16:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0151_meeting_summary_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturesession",
            name="lease_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="MeetingSpeaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("source_track_id", models.CharField(max_length=128)),
                ("source_key", models.CharField(max_length=128)),
                ("label", models.CharField(max_length=128)),
                (
                    "identity_type",
                    models.CharField(
                        choices=[("diarized", "Diarized"), ("unknown", "Unknown")],
                        max_length=16,
                    ),
                ),
                (
                    "capture_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.capturesession",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="core.meetingrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingOriginalSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("ingest_id", models.UUIDField(unique=True)),
                ("source_track_id", models.CharField(max_length=128)),
                ("source_sequence", models.PositiveIntegerField()),
                ("start_ms", models.PositiveBigIntegerField()),
                ("end_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("text", models.TextField()),
                ("language", models.CharField(blank=True, max_length=16)),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "capture_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_segments",
                        to="core.capturesession",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_segments",
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingspeaker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("payload", models.JSONField()),
                ("result", models.JSONField()),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.capturesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="unique_capture_operation"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="meetingspeaker",
            constraint=models.UniqueConstraint(
                fields=("capture_session", "source_track_id", "source_key"),
                name="unique_capture_track_speaker",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingoriginalsegment",
            constraint=models.UniqueConstraint(
                fields=("capture_session", "source_track_id", "source_sequence"),
                name="unique_capture_track_text_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingoriginalsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_sequence__gte", 1)),
                name="original_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingoriginalsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision", 1)), name="original_revision_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingoriginalsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_ms__isnull", True),
                    ("end_ms__gte", models.F("start_ms")),
                    _connector="OR",
                ),
                name="original_end_after_start",
            ),
        ),
    ]
