# Generated by Django 5.2.14 on 2026-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_independent_capture_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptdelivery',
            name='source_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
