# Generated by Django 5.2.14 on 2026-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0153_asr_source_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingsummaryversion",
            name="stage",
            field=models.CharField(
                choices=[
                    ("realtime", "Realtime"),
                    ("quick", "Quick"),
                    ("final", "Final"),
                ],
                default="final",
                max_length=16,
            ),
        ),
    ]
