# Generated by Django 5.2.14 on 2026-09-12 19:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0158_meeting_translation_control"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummaryReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("content", models.JSONField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "base_summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingsummaryversion",
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingsummaryreview",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_reviews",
                        to="core.meetingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ("-revision",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "revision"),
                        name="unique_summary_review_revision",
                    ),
                    models.UniqueConstraint(
                        fields=("author", "key"), name="unique_summary_review_intent"
                    ),
                ],
            },
        ),
    ]
