# Generated by Django 5.2.14 on 2026-09-12 20:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_human_summary_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummaryTaskLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('action_index', models.PositiveSmallIntegerField()),
                ('action_hash', models.CharField(max_length=64)),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('confirmed', models.JSONField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_task_links', to='core.meetingrecord')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.meetingsummaryreview')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('record', 'action_hash'), name='unique_record_review_action_task'), models.UniqueConstraint(fields=('author', 'key'), name='unique_review_action_task_intent')],
            },
        ),
    ]
