# Generated by Django 5.2.14 on 2026-09-12 20:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_reviewed_summary_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummaryTaskRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meetingsummarytasklink')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('author', 'key'), name='unique_summary_task_request')],
            },
        ),
    ]
