# Generated by Django 5.2.14 on 2026-09-12 20:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_summary_task_request_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecordQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('question', models.CharField(max_length=2000)),
                ('configuration', models.JSONField()),
                ('status', models.CharField(default='running', max_length=16)),
                ('deadline', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.meetingrecord')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.meetingtranscriptversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requested_by', 'key'), name='unique_record_question_intent')],
            },
        ),
    ]
