# Generated by Django 5.2.14 on 2026-09-12 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_record_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAudioManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('final_sequence', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=16)),
                ('duration_ms', models.PositiveBigIntegerField()),
                ('missing_sequences', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_manifest', to='core.capturesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptureAudioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('sequence', models.PositiveIntegerField()),
                ('start_ms', models.PositiveBigIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=500)),
                ('stored', models.BooleanField(default=False)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='core.capturesession')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('capture', 'sequence'), name='unique_capture_audio_chunk')],
            },
        ),
    ]
