# Generated by Django 5.2.14 on 2026-09-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_capture_audio_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureaudiomanifest',
            name='client_interrupted',
            field=models.BooleanField(default=False),
        ),
    ]
