# Generated by Django 5.2.14 on 2026-09-12 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_capture_audio_interruption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureTranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('generation', models.PositiveIntegerField()),
                ('inputs', models.JSONField()),
                ('configuration', models.JSONField()),
                ('status', models.CharField(default='queued', max_length=16)),
                ('worker_id', models.UUIDField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_inputs', models.PositiveIntegerField(default=0)),
                ('final_sequence', models.PositiveIntegerField(default=0)),
                ('text_bytes', models.PositiveIntegerField(default=0)),
                ('finish_hash', models.CharField(blank=True, max_length=64)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_jobs', to='core.capturesession')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='capturesession',
            name='active_transcription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='published_captures', to='core.capturetranscriptionjob'),
        ),
        migrations.AddField(
            model_name='meetingoriginalsegment',
            name='transcription_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='originals', to='core.capturetranscriptionjob'),
        ),
        migrations.AddConstraint(
            model_name='capturetranscriptionjob',
            constraint=models.UniqueConstraint(fields=('requested_by', 'key'), name='unique_capture_asr_intent'),
        ),
        migrations.AddConstraint(
            model_name='capturetranscriptionjob',
            constraint=models.UniqueConstraint(fields=('capture', 'generation'), name='unique_capture_asr_generation'),
        ),
        migrations.AddConstraint(
            model_name='capturetranscriptionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('capture',), name='one_active_capture_asr'),
        ),
        migrations.AddConstraint(
            model_name='capturetranscriptionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('worker_id',), name='one_running_capture_asr_worker'),
        ),
    ]
