# Generated by Django 5.2.14 on 2026-09-12 23:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0165_capture_transcription_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummaryExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("ai", "AI"), ("human", "Human")], max_length=8
                    ),
                ),
                ("source_id", models.UUIDField()),
                (
                    "language",
                    models.CharField(
                        choices=[("zh", "Chinese"), ("en", "English")], max_length=8
                    ),
                ),
                ("api_url", models.URLField(max_length=500)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("ready", "ready"),
                            ("uncertain", "uncertain"),
                            ("failed", "failed"),
                            ("unavailable", "unavailable"),
                            ("canceled", "canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("worker_id", models.UUIDField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("dispatch_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("create_started", models.BooleanField(default=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_exports",
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingsummaryreview",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingsummaryversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingSummaryExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("attempt", models.PositiveIntegerField()),
                (
                    "export",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="core.meetingsummaryexport",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meetingsummaryexport",
            constraint=models.UniqueConstraint(
                fields=(
                    "record",
                    "requested_by",
                    "source_kind",
                    "source_id",
                    "language",
                ),
                name="unique_summary_export_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingsummaryexportrequest",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "key"), name="unique_summary_export_intent"
            ),
        ),
    ]
