# Generated by Django 5.2.14 on 2026-09-13 00:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0166_meeting_summary_exports"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSummaryNotificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("recipient_ids", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_event",
                        to="core.meetingsummaryversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MeetingSummaryNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("recipient_sub", models.CharField(max_length=255)),
                ("source_metadata", models.JSONField()),
                ("api_url", models.URLField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                ("body_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("delivered", "delivered"),
                            ("uncertain", "uncertain"),
                            ("failed", "failed"),
                            ("unavailable", "unavailable"),
                            ("canceled", "canceled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("worker_id", models.UUIDField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("dispatch_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("bot_uid", models.UUIDField(blank=True, null=True)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("message_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("send_started", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_notifications",
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.meetingsummaryversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("summary", "recipient"),
                        name="unique_summary_notification_recipient",
                    )
                ],
            },
        ),
    ]
