# Generated by Django 5.2.14 on 2026-09-13 00:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0169_summary_share_receipts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingInterpretationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("organization_id_snapshot", models.UUIDField(blank=True, null=True)),
                ("target", models.CharField(max_length=8)),
                ("generation", models.PositiveIntegerField()),
                ("configuration", models.JSONField()),
                ("state", models.CharField(default="prepared", max_length=16)),
                ("worker_id", models.UUIDField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("stop_requested_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("finish_receipt", models.JSONField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretation_channels",
                        to="core.meetingsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingInterpretationCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("payload", models.JSONField()),
                ("result", models.JSONField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingInterpretationSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.meetinginterpretationchannel",
                    ),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretation_subscription",
                        to="core.meetingparticipation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="meetinginterpretationchannel",
            constraint=models.UniqueConstraint(
                fields=("session", "target", "generation"),
                name="unique_interpretation_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetinginterpretationchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["prepared", "starting", "translating", "stopping"])
                ),
                fields=("session", "target"),
                name="unique_live_interpretation_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetinginterpretationcommand",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="unique_interpretation_command"
            ),
        ),
    ]
