# Generated by Django 5.2.14 on 2026-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_interpretation_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginterpretationchannel',
            name='start_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
