# Generated by Django 5.2.14 on 2026-09-13 01:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_interpretation_start_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTranslationArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('source_id', models.UUIDField(unique=True)),
                ('source_kind', models.CharField(choices=[('channel', 'Channel'), ('private', 'Private')], max_length=16)),
                ('generation', models.PositiveIntegerField()),
                ('configuration', models.JSONField()),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('text_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='capturing', max_length=16)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_archives', to='core.meetingrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingTranslationSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('source_participation_id', models.UUIDField()),
                ('source_participant_sid', models.CharField(max_length=64)),
                ('response_id', models.CharField(max_length=128)),
                ('item_id', models.CharField(max_length=128)),
                ('direction', models.CharField(choices=[('forward', 'Forward'), ('reverse', 'Reverse')], max_length=8)),
                ('target', models.CharField(max_length=8)),
                ('text', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.meetingtranslationarchive')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('archive', 'source_participation_id', 'direction', 'response_id', 'item_id'), name='unique_translation_provider_item'), models.UniqueConstraint(fields=('archive', 'sequence'), name='unique_translation_archive_sequence')],
            },
        ),
    ]
