# Generated by Django 5.2.14 on 2026-09-13 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_translation_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturetranscriptionjob',
            name='live_manifest',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaptureTranscriptionInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('index', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.captureaudiochunk')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_inputs', to='core.capturetranscriptionjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'index'), name='unique_live_asr_input_index'), models.UniqueConstraint(fields=('job', 'chunk'), name='unique_live_asr_input_chunk')],
            },
        ),
    ]
