# Generated by Django 5.2.14 on 2026-09-13 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_capture_live_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureaudiochunk',
            name='audio_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaptureAudioCleanup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('complete', 'Complete')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_cleanup', to='core.capturesession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
