# Generated by Django 5.2.14 on 2026-09-13 10:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0174_capture_audio_cleanup"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudRecordingCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("payload", models.JSONField()),
                ("result", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("unknown", "unknown"),
                        ],
                        default="accepted",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_commands",
                        to="core.recording",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="uniq_cloud_recording_command"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("state__in", ["accepted", "running", "unknown"])
                        ),
                        fields=("recording",),
                        name="uniq_pending_cloud_rec_command",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", False),
                                ("state__in", ["succeeded", "failed"]),
                            ),
                            models.Q(
                                ("completed_at__isnull", True),
                                ("state__in", ["accepted", "running", "unknown"]),
                            ),
                            _connector="OR",
                        ),
                        name="cloud_rec_command_terminal_time",
                    ),
                ],
            },
        ),
    ]
