# Generated by Django 5.2.14 on 2026-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0175_cloud_recording_commands"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudrecordingcommand",
            name="lease_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cloudrecordingcommand",
            name="lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="cloudrecordingcommand",
            index=models.Index(
                fields=["state", "lease_until"], name="cloud_cmd_state_lease_idx"
            ),
        ),
    ]
