# Generated by Django 5.2.14 on 2026-09-13 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_cloud_recording_worker_leases'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureTranslationCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('payload', models.JSONField()),
                ('result', models.JSONField()),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capturesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_capture_translation_cmd')],
            },
        ),
        migrations.CreateModel(
            name='CaptureTranslationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('generation', models.PositiveIntegerField()),
                ('source_revision', models.PositiveIntegerField()),
                ('source_lease_hash', models.CharField(max_length=64)),
                ('organization_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('configuration', models.JSONField()),
                ('status', models.CharField(choices=[('starting', 'starting'), ('translating', 'translating'), ('stopping', 'stopping'), ('stopped', 'stopped'), ('incomplete', 'incomplete')], default='starting', max_length=16)),
                ('deadline', models.DateTimeField()),
                ('worker_id', models.UUIDField(blank=True, null=True)),
                ('begun_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('finish_hash', models.CharField(blank=True, max_length=64)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_runs', to='core.capturesession')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capture', 'generation'), name='unique_capture_translation_gen'), models.UniqueConstraint(condition=models.Q(('status__in', ['starting', 'translating', 'stopping'])), fields=('capture',), name='unique_active_capture_translation'), models.CheckConstraint(condition=models.Q(('generation__gte', 1), ('source_revision__gte', 1)), name='capture_translation_positive_gen'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', False), ('status__in', ['stopped', 'incomplete'])), models.Q(('ended_at__isnull', True), ('status__in', ['starting', 'translating', 'stopping'])), _connector='OR'), name='capture_translation_end_state')],
            },
        ),
    ]
