# Generated by Django 5.2.14 on 2026-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0177_capture_translation_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranslationsegment',
            name='source_capture_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtranslationarchive',
            name='source_kind',
            field=models.CharField(choices=[('channel', 'Channel'), ('private', 'Private'), ('capture', 'Capture')], max_length=16),
        ),
        migrations.AlterField(
            model_name='meetingtranslationsegment',
            name='source_participant_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='meetingtranslationsegment',
            name='source_participation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='meetingtranslationsegment',
            constraint=models.UniqueConstraint(condition=models.Q(('source_capture_id__isnull', False)), fields=('archive', 'source_capture_id', 'direction', 'response_id', 'item_id'), name='unique_capture_translation_item'),
        ),
    ]
