# Generated by Django 5.2.14 on 2026-09-15 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0178_capture_translation_archives"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedRecording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField(unique=True)),
                ("storage_name", models.CharField(max_length=500)),
                ("checksum", models.CharField(max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                ("configuration", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("submitting", "submitting"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("provider_task_id", models.CharField(blank=True, max_length=128)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("deadline", models.DateTimeField()),
                ("next_poll_at", models.DateTimeField()),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                (
                    "capture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.capturesession",
                    ),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_recording",
                        to="core.meetingrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_poll_at"], name="upload_asr_poll_idx"
                    )
                ],
            },
        ),
    ]
