# Generated by Django 5.2.14 on 2026-09-19 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_uploaded_recording_filetrans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingOriginalRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('revision', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.meetingoriginalsegment')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_revisions', to='core.meetingrecord')),
            ],
            options={
                'db_table': 'meet_meeting_original_revision',
                'ordering': ('original_id', '-revision'),
                'constraints': [models.UniqueConstraint(fields=('original', 'revision'), name='unique_original_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='original_revision_positive')],
            },
        ),
    ]
