# Generated by Django 5.2.14 on 2026-09-19 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_meetingspeaker_attributed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('key', models.UUIDField()),
                ('declared_name', models.CharField(max_length=255)),
                ('storage_name', models.CharField(max_length=500)),
                ('upload_id', models.CharField(max_length=512)),
                ('size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=16)),
                ('part_size', models.PositiveIntegerField()),
                ('configuration', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'open'), ('completed', 'completed'), ('aborted', 'aborted')], default='open', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meet_recording_upload_session',
                'indexes': [models.Index(fields=['owner', 'status'], name='upload_session_owner_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='unique_recording_upload_intent'), models.CheckConstraint(condition=models.Q(('part_size__gte', 5242880)), name='upload_part_size_reasonable'), models.CheckConstraint(condition=models.Q(('size__gte', 1)), name='upload_session_size_positive')],
            },
        ),
    ]
