# Generated by Django 5.2.14 on 2026-09-20 07:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0182_recording_upload_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptReplacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("find", models.CharField(max_length=200)),
                ("replacement", models.CharField(blank=True, max_length=200)),
                ("changes", models.JSONField()),
                ("record_revision", models.PositiveIntegerField()),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript_replacements",
                        to="core.meetingrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "key"),
                        name="unique_transcript_replacement_key",
                    )
                ],
            },
        ),
    ]
