# Generated by Django 5.2.14 on 2026-09-21 03:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0186_record_purge"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadTranscriptTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("target", models.CharField(max_length=8)),
                ("input_revision", models.PositiveIntegerField()),
                ("source", models.JSONField(default=list)),
                ("configuration", models.JSONField(default=dict)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("content", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("deadline", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_chunks", models.PositiveIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
                ("segment_count", models.PositiveIntegerField(default=0)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_translations",
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "deadline"],
                        name="upload_translation_deadline",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requested_by", "key"),
                        name="unique_upload_translation_key",
                    )
                ],
            },
        ),
    ]
