# Generated by Django 5.2.14 on 2026-09-22 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0188_capture_diagnostics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingprocessingjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("transcription", "Transcription"),
                    ("summary", "Summary"),
                    ("overview", "Overview"),
                    ("doc", "Document"),
                    ("delivery", "Delivery"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MeetingOverviewVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("content", models.JSONField()),
                ("model_used", models.CharField(max_length=128)),
                (
                    "input_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="overviews",
                        to="core.meetingtranscriptversion",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="overview_version",
                        to="core.meetingprocessingjob",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overview_versions",
                        to="core.meetingrecord",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
