# Generated by Django 5.2.14 on 2026-09-22 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0189_independent_record_overviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingCollaboration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("record", "Record"), ("minutes", "Minutes")],
                        max_length=10,
                    ),
                ),
                (
                    "link_scope",
                    models.CharField(
                        choices=[
                            ("private", "Collaborators"),
                            ("organization", "Organization"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_meeting_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_policies",
                        to="core.meetingrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingCollaborationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("result", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingcollaboration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("record", "Record"), ("minutes", "Minutes")],
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("editor", "Editor"),
                            ("manager", "Manager"),
                            ("none", "Removed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("media", models.BooleanField(default=False)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meetingcollaboration",
            constraint=models.UniqueConstraint(
                fields=("record", "scope"), name="unique_meeting_collaboration"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingcollaborationreceipt",
            constraint=models.UniqueConstraint(
                fields=("actor", "key"), name="unique_meeting_collaboration_receipt"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingcollaborator",
            constraint=models.UniqueConstraint(
                fields=("record", "scope", "user"), name="unique_meeting_collaborator"
            ),
        ),
    ]
