# Generated by Django 5.2.14 on 2026-09-22 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0190_independent_meeting_collaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingCollaborationNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("body", models.TextField(blank=True)),
                ("sender_uid", models.UUIDField(blank=True, null=True)),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=12)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="core.meetingcollaborationreceipt",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "recipient"),
                        name="unique_collaboration_notice",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingCollaborationTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("record", "Record"), ("minutes", "Minutes")],
                        max_length=10,
                    ),
                ),
                ("team", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("editor", "Editor"),
                            ("manager", "Manager"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_teams",
                        to="core.meetingrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "scope", "team"),
                        name="unique_meeting_collaboration_team",
                    )
                ],
            },
        ),
    ]
