# Generated by Django 5.2.14 on 2026-10-05 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_upgrade_qwen_omni_38'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySummaryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('uncertain', 'uncertain'), ('cancelled', 'cancelled')], default='running', max_length=16)),
                ('lease_until', models.DateTimeField()),
                ('source_state', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_summary_run', to='core.meetingsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
