# Generated by Django 5.2.14 on 2026-10-08 05:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_legacy_summary_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAIAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('model', models.CharField(max_length=100)),
                ('transport', models.CharField(max_length=16)),
                ('status', models.CharField(default='allocating', max_length=16)),
                ('lease_until', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status', 'lease_until'], name='core_direct_user_id_0044bb_idx'), models.Index(fields=['user', 'created_at'], name='core_direct_user_id_9c5550_idx')],
            },
        ),
    ]
