# Generated by Django 5.2.14 on 2026-10-09 18:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0200_speaker_identity_decisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceprintConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("allow_enrollment", models.BooleanField(default=False)),
                ("allow_accumulation", models.BooleanField(default=False)),
                ("allow_identification", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("granted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiceprint_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintConsentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("version", models.PositiveBigIntegerField()),
                ("generation", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("settings", "settings"),
                            ("delete", "delete"),
                            ("invalidate", "invalidate"),
                        ],
                        max_length=24,
                    ),
                ),
                ("permissions", models.JSONField()),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.voiceprintconsent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintDeletionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("owner_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("profile_id", models.UUIDField(blank=True, null=True)),
                ("request_key", models.UUIDField()),
                ("expected_version", models.PositiveBigIntegerField()),
                ("revoked_generation", models.PositiveBigIntegerField()),
                ("reason", models.CharField(default="user_deleted", max_length=24)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("receipt", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.voiceprintconsent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("feature_space", models.CharField(max_length=128)),
                ("generation", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("active", "active"),
                            ("paused", "paused"),
                            ("deleted", "deleted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "encrypted_key",
                    models.BinaryField(blank=True, default=bytes, max_length=256),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="core.voiceprintconsent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                ("consent_version", models.PositiveBigIntegerField()),
                ("permit_id", models.UUIDField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[("enrollment", "enrollment"), ("call", "call")],
                        max_length=16,
                    ),
                ),
                ("source_session_id", models.UUIDField(blank=True, null=True)),
                (
                    "source_track",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("start_ms", models.PositiveIntegerField(default=0)),
                ("end_ms", models.PositiveIntegerField()),
                ("audio_sha256", models.CharField(max_length=64)),
                (
                    "encrypted_audio",
                    models.BinaryField(blank=True, default=bytes, max_length=484160),
                ),
                (
                    "encrypted_embedding",
                    models.BinaryField(blank=True, default=bytes, max_length=32768),
                ),
                ("quality", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("ready", "ready"),
                            ("confirmed", "confirmed"),
                            ("rejected", "rejected"),
                            ("expired", "expired"),
                            ("deleted", "deleted"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="core.voiceprintprofile",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.meetingrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                ("device_group", models.CharField(default="default", max_length=24)),
                ("dimension", models.PositiveIntegerField()),
                (
                    "encrypted_vector",
                    models.BinaryField(blank=True, default=bytes, max_length=32768),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("paused", "paused"),
                            ("deleted", "deleted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="core.voiceprintprofile",
                    ),
                ),
                (
                    "support_samples",
                    models.ManyToManyField(
                        related_name="templates", to="core.voiceprintsample"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="voiceprintconsent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("user", "organization"),
                name="vp_consent_user_org_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintconsent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("user",),
                name="vp_consent_personal_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintconsent",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1), ("version__gte", 1)),
                name="vp_consent_positive_versions",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintconsentevent",
            constraint=models.UniqueConstraint(
                fields=("consent", "version"), name="vp_consent_event_version_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintdeletionjob",
            index=models.Index(
                fields=["status", "created_at"], name="core_voicep_status_3f4472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintdeletionjob",
            index=models.Index(
                fields=["owner_id", "organization_id", "revoked_generation"],
                name="core_voicep_owner_i_15dd11_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintdeletionjob",
            constraint=models.UniqueConstraint(
                fields=("owner_id", "request_key"), name="vp_delete_request_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintprofile",
            constraint=models.UniqueConstraint(
                fields=("consent", "feature_space"),
                name="vp_profile_scope_model_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintsample",
            index=models.Index(
                fields=["profile", "generation", "status"],
                name="core_voicep_profile_f24fc5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsample",
            constraint=models.UniqueConstraint(
                fields=("profile", "permit_id", "audio_sha256"),
                name="vp_sample_permit_digest_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsample",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_ms__gt", models.F("start_ms"))),
                name="vp_sample_positive_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprinttemplate",
            constraint=models.UniqueConstraint(
                fields=("profile", "generation", "device_group"),
                name="vp_template_device_unique",
            ),
        ),
    ]
