# Generated by Django 5.2.14 on 2026-10-09 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0202_voiceprint_policy_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceprintSampleDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("owner_id", models.UUIDField()),
                ("accepted", models.BooleanField()),
                ("consent_version", models.PositiveBigIntegerField()),
                ("generation", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="voiceprintsample",
            name="enrollment_slot",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VoiceprintEncodingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                            ("expired", "expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("retryable", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sample",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encoding_job",
                        to="core.voiceprintsample",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("owner_id", models.UUIDField()),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("request_key", models.UUIDField()),
                ("consent_version", models.PositiveBigIntegerField()),
                ("generation", models.PositiveBigIntegerField()),
                ("policy_version", models.PositiveBigIntegerField(default=0)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("challenges", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("closed", "closed"),
                            ("expired", "expired"),
                            ("canceled", "canceled"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="core.voiceprintprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="voiceprintsample",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="samples",
                to="core.voiceprintenrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsample",
            constraint=models.UniqueConstraint(
                condition=models.Q(("enrollment__isnull", False)),
                fields=("enrollment", "enrollment_slot"),
                name="vp_enrollment_slot_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsample",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("enrollment__isnull", True),
                    models.Q(
                        ("enrollment__isnull", False),
                        ("enrollment_slot__gte", 0),
                        ("enrollment_slot__isnull", False),
                        ("enrollment_slot__lte", 5),
                    ),
                    _connector="OR",
                ),
                name="vp_enrollment_slot_valid",
            ),
        ),
        migrations.AddField(
            model_name="voiceprintsampledecision",
            name="sample",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_decision",
                to="core.voiceprintsample",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintencodingjob",
            index=models.Index(
                fields=["status", "lease_until", "created_at"],
                name="core_voicep_status_72a889_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintencodingjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", 3)),
                name="vp_encoding_attempt_limit",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintenrollment",
            index=models.Index(
                fields=["owner_id", "created_at"], name="core_voicep_owner_i_535c86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintenrollment",
            constraint=models.UniqueConstraint(
                fields=("owner_id", "request_key"), name="vp_enrollment_request_unique"
            ),
        ),
    ]
