# Generated by Django 5.2.14 on 2026-10-10 00:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0205_voiceprint_quality_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerIdentityJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("requested_users", models.JSONField(default=list)),
                ("record_revision", models.PositiveIntegerField()),
                ("intent_digest", models.CharField(max_length=64)),
                ("source_digest", models.CharField(max_length=64)),
                ("candidate_digest", models.CharField(max_length=64)),
                ("threshold_digest", models.CharField(max_length=64)),
                ("threshold_version", models.CharField(max_length=128)),
                ("feature_space", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("canceled", "canceled"),
                            ("expired", "expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("retryable", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingspeaker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeakerIdentitySuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("result", models.CharField(max_length=32)),
                ("reason", models.CharField(max_length=64)),
                ("clip_count", models.PositiveSmallIntegerField(default=0)),
                ("speech_ms", models.PositiveIntegerField(default=0)),
                ("score", models.FloatField(blank=True, null=True)),
                ("margin", models.FloatField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("confirmed", "confirmed"),
                            ("rejected", "rejected"),
                            ("invalidated", "invalidated"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_suggestion_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestion",
                        to="core.speakeridentityjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="speakeridentityjob",
            index=models.Index(
                fields=["status", "lease_until", "created_at"],
                name="core_speake_status_a65446_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentityjob",
            constraint=models.UniqueConstraint(
                fields=("record", "speaker", "request_key"), name="identity_job_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentityjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", 3)),
                name="identity_job_attempt_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentitysuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("clip_count__lte", 12)),
                name="identity_suggestion_clip_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentitysuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", -1), ("score__lte", 1)),
                    _connector="OR",
                ),
                name="identity_suggestion_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentitysuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("margin__isnull", True),
                    models.Q(("margin__gte", 0), ("margin__lte", 2)),
                    _connector="OR",
                ),
                name="identity_suggestion_margin_range",
            ),
        ),
    ]
