# Generated by Django 5.2.14 on 2026-10-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0206_speaker_identity_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakeridentitydecision",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="identity_decisions",
                to="core.speakeridentitysuggestion",
            ),
        ),
        migrations.AddField(
            model_name="speakeridentityjob",
            name="candidate_context_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="speakeridentityjob",
            name="presentation_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="speakeridentityjob",
            name="source_generation_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="speakeridentitysuggestion",
            name="query_intervals",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
