# Generated by Django 5.2.14 on 2026-10-10 01:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0207_speaker_identity_context_proofs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerIdentityRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("input_digest", models.CharField(max_length=64)),
                ("target_ids", models.JSONField()),
                ("requested_users", models.JSONField()),
                ("record_revision", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.meetingrecord",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="speakeridentityjob",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="core.speakeridentityrequest",
            ),
        ),
        migrations.AddIndex(
            model_name="speakeridentityrequest",
            index=models.Index(
                fields=["record", "created_at"], name="core_speake_record__a3019b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="speakeridentityrequest",
            constraint=models.UniqueConstraint(
                fields=("record", "request_key"), name="identity_record_request"
            ),
        ),
    ]
