# Generated by Django 5.2.14 on 2026-10-10 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0208_speaker_identity_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedrecording',
            name='identity_error',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='uploadedrecording',
            name='identity_state',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='RecordingImportInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('record_uuid', models.UUIDField()),
                ('attempt', models.PositiveIntegerField()),
                ('lease_token', models.UUIDField()),
                ('source_digest', models.CharField(max_length=64)),
                ('receipt', models.JSONField(blank=True, default=dict)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='preparing', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('write_until', models.DateTimeField()),
                ('next_cleanup_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_inputs', to='core.uploadedrecording')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_cleanup_at'], name='import_input_cleanup_idx')],
            },
        ),
    ]
