# Generated by Django 5.2.14 on 2026-10-10 06:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0209_recording_identity_preflight"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingIdentityDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("request_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("record_revision", models.PositiveIntegerField()),
                ("configuration_digest", models.CharField(max_length=64)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_dispatch",
                        to="core.uploadedrecording",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="identity_dispatch_due_idx",
                    )
                ],
            },
        ),
    ]
