# Generated by Django 5.2.14 on 2026-10-10 08:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0210_recording_identity_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingoriginalsegment",
            name="derivation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="meetingoriginalsegment",
            name="inherited_correction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inheriting_originals",
                to="core.meetingoriginalrevision",
            ),
        ),
        migrations.AddField(
            model_name="meetingoriginalsegment",
            name="parent_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="diarization_children",
                to="core.meetingoriginalsegment",
            ),
        ),
        migrations.CreateModel(
            name="CaptureDiarizationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                ("generation", models.PositiveIntegerField()),
                ("source_revision", models.PositiveIntegerField()),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("inputs", models.JSONField()),
                ("configuration", models.JSONField()),
                ("status", models.CharField(default="queued", max_length=16)),
                ("worker_id", models.UUIDField(blank=True, null=True)),
                ("deadline", models.DateTimeField()),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("result_hash", models.CharField(blank=True, max_length=64)),
                ("publication_hash", models.CharField(blank=True, max_length=64)),
                ("published_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diarization_jobs",
                        to="core.capturesession",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_derivation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.capturediarizationjob",
                    ),
                ),
                (
                    "source_transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.capturetranscriptionjob",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="capturesession",
            name="active_diarization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="published_captures",
                to="core.capturediarizationjob",
            ),
        ),
        migrations.AddField(
            model_name="meetingoriginalsegment",
            name="diarization_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="originals",
                to="core.capturediarizationjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingoriginalsegment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("derivation", {}),
                        ("diarization_job__isnull", True),
                        ("inherited_correction__isnull", True),
                        ("parent_original__isnull", True),
                    ),
                    models.Q(
                        ("diarization_job__isnull", False),
                        ("parent_original__isnull", False),
                        ("transcription_job__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="original_derivation_has_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturediarizationjob",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "key"), name="unique_capture_diarize_intent"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturediarizationjob",
            constraint=models.UniqueConstraint(
                fields=("capture", "generation"), name="unique_capture_diarize_gen"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturediarizationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("capture",),
                name="one_active_capture_diarize",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturediarizationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("generation__gte", 1), ("source_revision__gte", 1)),
                name="capture_diarize_positive",
            ),
        ),
    ]
