# Generated by Django 5.2.14 on 2026-10-10 09:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def align_existing_phases(apps, schema_editor):
    jobs = apps.get_model("core", "CaptureDiarizationJob").objects.using(
        schema_editor.connection.alias
    )
    jobs.filter(status="succeeded").update(phase="completed")
    jobs.filter(status="failed").update(phase="failed")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0211_capture_diarization_generations"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturediarizationjob",
            name="begun_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="next_poll_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="phase",
            field=models.CharField(default="preparing", max_length=16),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="poll_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="preparation_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="provider_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="provider_task_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="CaptureDiarizationInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("record_uuid", models.UUIDField(db_index=True)),
                ("lease_token", models.UUIDField()),
                ("source_digest", models.CharField(max_length=64)),
                ("storage_digest", models.CharField(max_length=64)),
                ("receipt", models.JSONField(blank=True, default=dict)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("duration_ms", models.PositiveIntegerField()),
                ("status", models.CharField(default="preparing", max_length=16)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("write_until", models.DateTimeField()),
                (
                    "next_cleanup_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_inputs",
                        to="core.capturediarizationjob",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="capturediarizationjob",
            name="input",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="selected_jobs",
                to="core.capturediarizationinput",
            ),
        ),
        migrations.AddIndex(
            model_name="capturediarizationinput",
            index=models.Index(
                fields=["status", "next_cleanup_at"], name="capture_input_cleanup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturediarizationinput",
            constraint=models.UniqueConstraint(
                fields=("job", "lease_token"), name="unique_capture_input_lease"
            ),
        ),
        migrations.AddIndex(
            model_name="capturediarizationjob",
            index=models.Index(
                fields=["status", "next_poll_at"], name="capture_diarize_due_idx"
            ),
        ),
        migrations.RunPython(align_existing_phases, migrations.RunPython.noop),
    ]
