# Generated by Django 5.2.14 on 2026-10-10 12:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0212_capture_diarization_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceprintSamplingTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("livekit_track_sid", models.CharField(max_length=64, unique=True)),
                ("source", models.CharField(max_length=24)),
                ("media_type", models.CharField(max_length=8)),
                ("published_at", models.DateTimeField()),
                ("unpublished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiceprint_tracks",
                        to="core.meetingparticipation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintSamplingPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("source_session_id", models.UUIDField()),
                ("source_track_sid", models.CharField(max_length=64)),
                ("livekit_room_sid", models.CharField(max_length=64)),
                ("participant_sid", models.CharField(max_length=64)),
                ("participant_identity", models.CharField(max_length=255)),
                ("request_key", models.UUIDField()),
                ("consent_version", models.PositiveBigIntegerField()),
                ("generation", models.PositiveBigIntegerField()),
                ("policy_version", models.PositiveBigIntegerField()),
                ("control_revision", models.PositiveBigIntegerField()),
                ("device_group", models.CharField(max_length=16)),
                ("max_duration_ms", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "issued"),
                            ("canceled", "canceled"),
                            ("expired", "expired"),
                            ("consumed", "consumed"),
                        ],
                        default="issued",
                        max_length=16,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sampling_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sampling_permits",
                        to="core.voiceprintprofile",
                    ),
                ),
                (
                    "sample",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sampling_permit",
                        to="core.voiceprintsample",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permits",
                        to="core.voiceprintsamplingtrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceprintSamplingControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("paused", models.BooleanField(default=False)),
                ("shared_microphone", models.BooleanField(default=True)),
                (
                    "device_group",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiceprint_control",
                        to="core.meetingparticipation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="vp_control_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("device_group__in", ["", "headset", "handset", "computer"])
                        ),
                        name="vp_control_device_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="voiceprintsamplingtrack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unpublished_at__isnull", True),
                    ("unpublished_at__gte", models.F("published_at")),
                    _connector="OR",
                ),
                name="vp_track_end_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprintsamplingpermit",
            index=models.Index(
                fields=["owner", "created_at"], name="vp_sampling_owner_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsamplingpermit",
            constraint=models.UniqueConstraint(
                fields=("track", "request_key"), name="vp_sampling_request_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsamplingpermit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "issued")),
                fields=("track", "profile"),
                name="vp_sampling_one_issued",
            ),
        ),
        migrations.AddConstraint(
            model_name="voiceprintsamplingpermit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_duration_ms__gte", 3000), ("max_duration_ms__lte", 10000)
                ),
                name="vp_sampling_clip_bound",
            ),
        ),
    ]
