# Generated by Django 5.2.14 on 2026-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0213_voiceprint_sampling_permits"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprintsamplingcontrol",
            name="stop_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
