# Generated by Django 5.2.14 on 2026-10-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0214_voiceprint_sampling_stop_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiceprinttemplate",
            name="basis",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
