# Generated by Django 5.2.14 on 2026-10-10 14:44

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0215_voiceprint_device_template_basis"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceprintContributionRemoval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("sample_uuid", models.UUIDField(unique=True)),
                ("profile_uuid", models.UUIDField()),
                ("owner_uuid", models.UUIDField()),
                ("organization_uuid", models.UUIDField(blank=True, null=True)),
                ("generation", models.PositiveBigIntegerField()),
                ("templates", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("purged", "purged"),
                            ("complete", "complete"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="core_voicep_status_e2a3ba_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoiceprintSourceRemoval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("session", "session"),
                            ("track", "track"),
                            ("record", "record"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_uuid", models.UUIDField()),
                (
                    "source_session_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "track_digest",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "source_uuid"), name="vp_source_removal_unique"
                    )
                ],
            },
        ),
    ]
