# Generated by Django 5.2.14 on 2026-10-10 15:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0216_voiceprint_source_removal"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceprintSamplingActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("sampling", "sampling"),
                            ("uploading", "uploading"),
                            ("stopped", "stopped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "permit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.voiceprintsamplingpermit",
                    ),
                ),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="core.voiceprintsamplingtrack",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VoiceprintSamplingDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("ready", "ready"),
                            ("idle", "idle"),
                            ("failed", "failed"),
                            ("ended", "ended"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("room_sid", models.CharField(blank=True, default="", max_length=64)),
                (
                    "agent_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=32)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voiceprint_dispatch",
                        to="core.meetingsession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="core_voicep_status_5ff88d_idx",
                    )
                ],
            },
        ),
    ]
