"""Explicit consent, server scheduling, shutdown races and no automatic paid retries."""

import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import timedelta
from threading import Barrier
from unittest.mock import patch

from django.db import close_old_connections
from django.utils import timezone

import pytest

from core import models
from core.factories import UserFactory
from core.services.meeting_records import RecordConflict, transition_job
from core.services.meeting_summary_automation import (
    control_automation,
    tick_automation,
    tick_automations,
)
from core.services.meeting_summary_requests import SummaryRequestDenied
from core.tests.services.test_meeting_records import client_for, online_note
from core.tests.services.test_meeting_summary_requests import payload, post
from core.tests.services.test_meeting_summary_versions import output
from core.tests.services.test_staged_summaries import complete, live_note

pytestmark = pytest.mark.django_db


@pytest.fixture(autouse=True)
def enabled(settings):
    settings.MEETING_RECORDS_ENABLED = True
    settings.MEETING_VERSIONED_SUMMARY_ENABLED = True
    settings.MEETING_SUMMARY_REQUESTS_ENABLED = True
    settings.MEETING_STAGED_SUMMARY_ENABLED = True
    settings.MEETING_SUMMARY_AUTOMATION_ENABLED = True
    settings.CELERY_ENABLED = True
    settings.DASHSCOPE_API_KEY = "isolated-test-only"
    with patch("meet.celery_app.app.send_task"):
        yield


def start(user, record):
    """No job is generated by the consent command itself."""
    return control_automation(
        record.pk, user, uuid.uuid4(), {"enabled": True, "expected_revision": 0}
    )[1]


def test_no_implicit_consent_and_flag_cannot_start_any_record(settings):
    user, _, _, record = live_note()
    assert tick_automations() == 0
    assert not record.processing_jobs.exists()
    settings.MEETING_SUMMARY_AUTOMATION_ENABLED = False
    with pytest.raises(RecordConflict):
        start(user, record)
    assert not models.MeetingSummaryAutomation.objects.exists()


def test_toggle_replay_returns_historic_result_without_reenabling():
    user, _, _, record = live_note()
    key = uuid.uuid4()
    body = {"enabled": True, "expected_revision": 0}
    first, automation, _ = control_automation(record.pk, user, key, body)
    control_automation(
        record.pk, user, uuid.uuid4(), {"enabled": False, "expected_revision": 1}
    )
    replay, current, repeated = control_automation(record.pk, user, key, body)
    assert repeated and replay.pk == first.pk
    assert replay.result["enabled"] is True
    assert current.enabled is False and current.revision == 2
    with pytest.raises(RecordConflict):
        control_automation(record.pk, user, key, {**body, "enabled": False})
    assert tick_automation(automation.pk) is False


def test_scheduler_creates_one_intent_and_frozen_control_fence():
    user, _, _, record = live_note()
    automation = start(user, record)
    assert tick_automation(automation.pk) is True
    assert tick_automation(automation.pk) is False
    job = record.processing_jobs.get()
    assert job.configuration["stage"] == "realtime"
    assert job.configuration["automation_id"] == str(automation.pk)
    assert job.configuration["automation_revision"] == 1
    assert job.user_requests.count() == 1
    assert complete(job)
    assert tick_automation(automation.pk) is False
    assert record.processing_jobs.count() == 1


@pytest.mark.parametrize("stop", ["toggle", "access", "flag"])
def test_stop_or_revocation_during_provider_call_never_publishes(stop, settings):
    user, session, _, record = live_note()
    automation = start(user, record)
    tick_automation(automation.pk)
    job = record.processing_jobs.get()

    def reply(**kwargs):
        if stop == "toggle":
            control_automation(
                record.pk,
                user,
                uuid.uuid4(),
                {"enabled": False, "expected_revision": 1},
            )
        elif stop == "access":
            models.ResourceAccess.objects.filter(
                resource=session.room, user=user
            ).delete()
        else:
            settings.MEETING_SUMMARY_AUTOMATION_ENABLED = False
        return output(job)

    assert complete(job, reply) is None
    assert not record.summary_versions.exists()
    job.refresh_from_db()
    assert job.status == "canceled"


def test_quick_then_final_run_without_browser_and_do_not_repeat_completed_cost():
    user, _, _, record = online_note()
    automation = start(user, record)
    assert tick_automation(automation.pk)
    quick = record.processing_jobs.get()
    assert quick.configuration["stage"] == "quick"
    assert complete(quick)
    assert tick_automation(automation.pk)
    final = record.processing_jobs.order_by("-generation").first()
    assert final.configuration["stage"] == "final"
    assert complete(final)
    for _ in range(3):
        assert tick_automation(automation.pk) is False
    automation.refresh_from_db()
    assert automation.state == "completed"
    assert record.summary_versions.count() == 2


def test_failed_output_stays_visible_and_no_paid_auto_retry():
    user, _, _, record = live_note()
    automation = start(user, record)
    tick_automation(automation.pk)
    job = record.processing_jobs.get()
    assert complete(job, lambda **kwargs: "invalid") is None
    for _ in range(3):
        assert tick_automation(automation.pk) is False
    job.refresh_from_db()
    automation.refresh_from_db()
    assert job.attempt == 1 and record.processing_jobs.count() == 1
    assert (
        automation.state == "needs_attention"
        and automation.error_code == "invalid_output"
    )


def test_explicit_retry_after_stopping_automation_is_a_manual_attempt():
    user, _, _, record = live_note()
    automation = start(user, record)
    tick_automation(automation.pk)
    job = record.processing_jobs.get()
    assert complete(job, lambda **kwargs: "invalid") is None
    control_automation(
        record.pk, user, uuid.uuid4(), {"enabled": False, "expected_revision": 1}
    )
    response = post(
        user, record, {**payload(record, job, "retry"), "stage": "realtime"}
    )
    assert response.status_code == 202
    job.refresh_from_db()
    assert "automation_id" not in job.configuration
    assert complete(job)


def test_scheduler_recovers_stuck_own_worker_without_repeating_provider():
    user, _, _, record = live_note()
    automation = start(user, record)
    tick_automation(automation.pk)
    job = record.processing_jobs.get()
    transition_job(job.pk, attempt=1, target="running")
    models.MeetingProcessingJob.objects.filter(pk=job.pk).update(
        updated_at=timezone.now() - timedelta(minutes=11)
    )
    assert tick_automation(automation.pk) is False
    job.refresh_from_db()
    assert job.status == "failed" and job.error_code == "worker_timeout"


def test_stop_available_when_rollout_disabled_and_read_share_cannot_toggle(settings):
    user, _, _, record = live_note()
    automation = start(user, record)
    reader = UserFactory()
    models.MeetingRecordAccess.objects.create(
        record=record, user=reader, read_summary=True
    )
    url = f"/api/v1.0/meeting-records/{record.pk}/summary-automation/"
    assert client_for(reader).get(url).json()["can_control"] is False
    with pytest.raises(SummaryRequestDenied):
        control_automation(
            record.pk, reader, uuid.uuid4(), {"enabled": False, "expected_revision": 1}
        )
    settings.MEETING_SUMMARY_AUTOMATION_ENABLED = False
    response = client_for(user).post(
        url,
        {"enabled": False, "expected_revision": 1},
        format="json",
        HTTP_IDEMPOTENCY_KEY=str(uuid.uuid4()),
    )
    assert (
        response.status_code == 200 and response.json()["current"]["enabled"] is False
    )
    automation.refresh_from_db()
    assert automation.state == "off"


def test_revoked_controller_disables_and_outbox_failure_is_recoverable(
    django_capture_on_commit_callbacks,
):
    user, session, _, record = live_note()
    automation = start(user, record)
    with patch("meet.celery_app.app.send_task", side_effect=RuntimeError("redacted")):
        with django_capture_on_commit_callbacks(execute=True):
            tick_automation(automation.pk)
    intent = record.summary_requests.get()
    intent.refresh_from_db()
    assert intent.dispatch_state == "pending"
    models.MeetingSummaryRequest.objects.filter(pk=intent.pk).update(
        dispatch_attempted_at=timezone.now() - timedelta(seconds=31)
    )
    assert tick_automations() == 0
    intent.refresh_from_db()
    assert intent.dispatch_state == "sent"
    models.ResourceAccess.objects.filter(resource=session.room, user=user).delete()
    assert tick_automation(automation.pk) is False
    automation.refresh_from_db()
    assert not automation.enabled and automation.error_code == "permission_revoked"


def test_lost_queue_message_resends_same_attempt_once_per_interval(
    django_capture_on_commit_callbacks,
):
    user, _, _, record = live_note()
    automation = start(user, record)
    with django_capture_on_commit_callbacks(execute=True):
        tick_automation(automation.pk)
    intent = record.summary_requests.get()
    job = intent.job
    models.MeetingSummaryRequest.objects.filter(pk=intent.pk).update(
        dispatch_attempted_at=timezone.now() - timedelta(seconds=31)
    )
    with patch("meet.celery_app.app.send_task") as send:
        with django_capture_on_commit_callbacks(execute=True):
            assert tick_automation(automation.pk) is False
        with django_capture_on_commit_callbacks(execute=True):
            assert tick_automation(automation.pk) is False
        assert send.call_count == 1
        assert send.call_args.kwargs["args"] == [str(job.pk), 1]
    assert record.processing_jobs.count() == record.summary_requests.count() == 1


@pytest.mark.django_db(transaction=True)
def test_two_schedulers_serialize_one_intent():
    user, _, _, record = live_note()
    automation = start(user, record)
    barrier = Barrier(2)

    def run():
        close_old_connections()
        try:
            barrier.wait(timeout=5)
            return tick_automation(automation.pk)
        finally:
            close_old_connections()

    with ThreadPoolExecutor(max_workers=2) as pool:
        results = list(pool.map(lambda _: run(), range(2)))
    assert sorted(results) == [False, True]
    assert record.processing_jobs.count() == record.summary_requests.count() == 1
